### ISSUE TITLE
can't use babel to convert es6 to es5

### ISSUE THREAD

**Issue by tantao9323** [robinvdvleuten/vuex-persistedstate#105]
**I use vue-cli and npm run build ,it can't be converted from es6 to es5 .**

**It's packed into verdor.js and console error："Uncaught SyntaxError: Use of const in strict mode."**

**How to deal with it?**

**Comment by robinvdvleuten** [comment]
That looks like an issue in your build setup to me and not to this plugin. I cannot help you with that, sorry.
