### ISSUE TITLE
How to fullfil states for each store module when rehydrating?

### ISSUE THREAD

**Issue by mobilesite** [robinvdvleuten/vuex-persistedstate#106]
My question is:

I have a list of modules, and i want to fulfill some other states in each module when i rehydrate the states, just like the REHYDRATE action in redux-persist can do.

Would you please give me some help? Thank you!

**Comment by robinvdvleuten** [comment]
Hi @mobilesite, this functionality is out of scope for this plugin and I suggest seeking support at the Vuex community itself.
