### ISSUE TITLE
LocalStorage fails in Safari private mode

### ISSUE THREAD

**Issue by nicooprat** [robinvdvleuten/vuex-persistedstate#107]
Looks like Safari has a pretty strange behavior with local/sessionStorage when being in private mode, it just throws an unrelated error: https://stackoverflow.com/a/14555361/758728

Would you mind adding this localStorage support check?

**Comment by Snowshield** [comment]
Is it not a support check in index.js from **line 9** ?

  ```
function canWriteStorage(storage) {
    try {
      storage.setItem('@@', 1);
      storage.removeItem('@@');
      return true;
    } catch (e) {}

    return false;
  }
```

**Comment by nicooprat** [comment]
Right, didn't see that. Looks like the `return` statement is outside the `catch` scope, is it normal? Here's the code from StackOverflow answer:

```js
try 
    {
        storage.setItem(testKey, '1');
        storage.removeItem(testKey);
        return localStorageName in win && win[localStorageName];
    } 
    catch (error) 
    {
        return false;
    }
```

Here's the error given in iOS 10.3 in private mode:

![capture d ecran 2018-01-01 a 19 49 09](https://user-images.githubusercontent.com/645641/34470212-e5eeab66-ef2c-11e7-9f58-7bf747a3534e.jpg)

**Comment by robinvdvleuten** [comment]
It is ok to have the return statement outside the catch, the catch does nothing in this case. And it seems that the check is doing its work correctly as you can see on [line 52](https://github.com/robinvdvleuten/vuex-persistedstate/blob/master/index.js#L52). You need to build some functionality around it yourself I am afraid to handle private visitors.
