### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by AmauryG13** [robinvdvleuten/vuex-persistedstate#11]
Do you think of encrypting datas saved in localstorage or set with a cookie ?

**Comment by robinvdvleuten** [comment]
@AmauryG13 Encrypting client-side is in no way secure if the key is also known client-side. The best way you can go is to make sure your app is only accessible through https. See this link for more information (https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2011/august/javascript-cryptography-considered-harmful/)
