### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by cybibo** [robinvdvleuten/vuex-persistedstate#110]
in 
node_modules/vuex-persistedstate/index.js

import merge from 'deepmerge';
import shvl from 'shvl';

export default function(options, storage, key) {
  options = options || {};
  storage = options.storage || (window && window.localStorage);

**Comment by robinvdvleuten** [comment]
What is your issue exactly? As you can see, this inline check already catches "window undefined" issues. Please submit a proper issue with the default issue template.
