### ISSUE TITLE
Local Storage is not created.

### ISSUE THREAD

**Issue by yashnerella** [robinvdvleuten/vuex-persistedstate#111]
**vuex-persistedstate doesn't work in my case.** This is the store setup that i currently have: 

import Vue from 'vue'
import Vuex from 'vuex'
import createPersistedState from 'vuex-persistedstate'

import dashboard from './modules/dashboard'
import configuration from './modules/configuration'

Vue.use(Vuex)

/**
* ROOT STATE
* Dashboard & Configuration modules incorporated into root state
*/

const store = new Vuex.Store({
	modules: {
		dashboard,
		configuration
		//Brand module is going to be loaded dynamically (@creation of RouteGenerator.vue)
	},
	plugins: [createPersistedState()]
})

export default store;

When i run my application. I do not see anything in my browser's local storage. 

Could you please provide an extensive example on how to use this plugin? The example that you provided in the readme doesn't explain everything in a clear fashion. 

Thanks.

**Comment by robinvdvleuten** [comment]
I don't know what could be extended to the README to make it more clearer. If you have any suggestions, please submit a PR. What do you except to see? If you initiallize your state without dispatching any actions, nothing will show up in your local storage.
