### ISSUE TITLE
Persist data for some states

### ISSUE THREAD

**Issue by Mrkisha** [robinvdvleuten/vuex-persistedstate#112]
I could not find a way to persist data for just few states that I want to keep track of.
I've tried with filter option, but it seems as its not working or I'm not using it in a right way.

Has anyone done this before?

**Comment by nikugogoi** [comment]
use `paths` option

**Comment by Mrkisha** [comment]
@nikugogoi Can you please give me an example?

**Comment by martijnvanloon** [comment]
can you give an example after finding the answer?
