### ISSUE TITLE
Change the key of the cookie on the fly?

### ISSUE THREAD

**Issue by poldixd** [robinvdvleuten/vuex-persistedstate#113]
thanks for the vuex plugin!

Is it possible to change the key of the cookie on the fly? I need to save informations in two separate cookies.

**Comment by robinvdvleuten** [comment]
The easiest thing would be to add your own "storage" that sets the correct cookie name according to the key. See https://github.com/robinvdvleuten/vuex-persistedstate#customize-storage

**Comment by J4si3k** [comment]
could you add use case?
