### ISSUE TITLE
Custom processing of state @ rehydration?

### ISSUE THREAD

**Issue by claytonrcarter** [robinvdvleuten/vuex-persistedstate#114]
What is the recommended way to do some custom processing when the state is rehydrated?

My use case is that I have some items in my state that are JS classes w/ data properties and methods. Because localStorage is JSON, the methods are lost when the state is rehydrated, though the data properties come through just fine.

Right now, I have to recreate the entire `getState` method, processing the state before it's returned:

```
createPersistedState({
    getState(key, storage, value) {
        try {
            var state = (value = storage.getItem(key)) && value !== 'undefined'
                        ? JSON.parse(value)
                        : undefined;

            state.items = state.items.map(i => new Item(i))

            return state
        } catch (err) {}

        return undefined;
    }})
```

Ideally, there could be a callback that's called w/ the rehydrated state just before the state is replaced. In my case, I would something like this would be great:
```
createPersistedState({
    rehydratedStateCallback: (state) => { 
        state.items = state.items.map(i => new Item(i)); 
        return state; 
    }})
```

**Comment by robinvdvleuten** [comment]
What you could do is to handle this yourself with Vuex's own functionality;

```js
const state = store.state

// ... process the state yourself 

store.replaceState(state)
```

And make sure you call this after the plugin is registered and the store instance created.

**Comment by robinvdvleuten** [comment]
Seems that my answer solved the case, I am gonna close it now.

**Comment by luceos** [comment]
Just curious @robinvdvleuten whether you considered the `hydrate` and `rehydrated` callbacks based on this issue or that it is out of the question anyway?
