### ISSUE TITLE
Array values does not persist when cookies are used instead of localstorage.

### ISSUE THREAD

**Issue by bharathvaj1995** [robinvdvleuten/vuex-persistedstate#115]
**Do you want to request a *feature* or report a *bug*?**
Bug. I ma using latest version.
**What is the current behavior?**
Array values are not saved into cookies

**If the current behavior is a bug, please provide the steps to reproduce.**
Just store any array value using jscookie as storage as mentioned in the docs.

**What is the expected behavior?**
Should persist the even the array value as localstorage.

**Comment by robinvdvleuten** [comment]
Thanks for reporting the issue! Could you try to json stringify the value before persisting it to cookies?

**Comment by robinvdvleuten** [comment]
I you do something like this, you're issue is probably solved;

```js
const store = new Store({
  // ...
  plugins: [
    createPersistedState({
      storage: {
        getItem: key => JSON.parse(Cookies.get(key)),
        setItem: (key, value) => Cookies.set(key, JSON.stringify(value)),
        // ...
      }
    })
  ]
})
```
