### ISSUE TITLE
Throws warning if Vuex is in strict mode

### ISSUE THREAD

**Issue by ffxsam** [robinvdvleuten/vuex-persistedstate#118]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
vuex-persist causes an exception when Vuex is in strict mode

**If the current behavior is a bug, please provide the steps to reproduce.**
Set up the vuex-persist plugin on a store.

![image](https://user-images.githubusercontent.com/12532733/36633225-36cfd4ac-1957-11e8-82b9-09766977fb29.png)

**Comment by kanatkubash** [comment]
Any feedback on this?

**Comment by robinvdvleuten** [comment]
If this is still relevant, please open a new issue.
