### ISSUE TITLE
add encryption

### ISSUE THREAD

**Issue by mvanroon** [robinvdvleuten/vuex-persistedstate#120]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Not implemented

**What is the expected behavior?**
Vuex store should optionally be stored encrypted

**If this is a feature request, what is motivation or use case for changing the behavior?**
Because some data in the persisted state (like JWT tokens) might be sensitive data and could potentially be used maliciously. For example: https://github.com/maxdeviant/redux-persist-transform-encrypt

**Comment by robinvdvleuten** [comment]
@mvanroon thanks for your suggestion, but keep in mind that storing anything client side and decrypting it in the same place is never secure. That's really what they call security by obscurity. If you need to put sensitive data into a JWT, you are using JWTs the wrong way I am afraid.

**Comment by mvanroon** [comment]
You're right. Thanks.

**Comment by ajmas** [comment]
While @robinvdvleuten is right, if you really need to do anything like this for other reason, then you can look at providing your own logic in the `storage.getItem()` and `storage.setItem()` methods. See the example in the readme where cookies are used for storage.
