### ISSUE TITLE
Expected Object, got String.

### ISSUE THREAD

**Issue by shubich** [robinvdvleuten/vuex-persistedstate#127]
```javascript
const state = {
  ...
  startDate: moment([2018, 9, 1]),
  endDate: moment(),
};
```
```javascript
export default new Vuex.Store({
  modules: {
    myModule,
  },
  strict: debug,
  plugins: [createPersistedState({ storage: window.sessionStorage })],
});
```

`error`: Invalid prop: type check failed for prop "date". Expected Object, got String.

**Comment by robinvdvleuten** [comment]
This is expected behaviour of the plugin, as everything is JSON encoded / decoded. The moment instance is encoded to a date string before stored in the localstorage instance.
