### ISSUE TITLE
nuxt TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by jjjachyty** [robinvdvleuten/vuex-persistedstate#134]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**

when i use in nuxt ,like this

```
sessionStorage.js
import createPersistedState from 'vuex-persistedstate'

export default ({store, isHMR, isServer, isClient}) => {
  if (isHMR) return

  if (isClient) {
    window.onNuxtReady((nuxt) => {
      createPersistedState()(store) // vuex plugins can be connected to store, even after creation
    })
  }
}

nuxt.config.js

  plugins: [
    { src: '~/plugins/sessionStorage.js', ssr: false }
  ],

```

￼
![1523351366904](https://user-images.githubusercontent.com/7439418/38547587-01a837e8-3ce2-11e8-87c7-fba72e49cd89.jpg)

￼

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by robinvdvleuten** [comment]
Please see #132, you should upgrade the plugin to version v2.5.2.

**Comment by jjjachyty** [comment]
when i user 2.5.2 ,the vuex store has userInfo valus,but when i use this.$store.state.user.userInfo was null ?

nuxt plugins js like this 
```export default ({ store, isHMR, isClient }) => {
  if (isHMR) return
  if (isClient) {
    window.onNuxtReady((nuxt) => {
      createPersistedState({ storage: window.sessionStorage })(store)
    })
  }
} 
```

![bug](https://user-images.githubusercontent.com/7439418/38592836-edf0d720-3d70-11e8-9a36-553df9bb4013.jpg)
@robinvdvleuten
