### ISSUE TITLE
its unclear that how to use  in nuxt framework.

### ISSUE THREAD

**Issue by sudhir600** [robinvdvleuten/vuex-persistedstate#137]
where is the uses section for "nuxt"
I did the changes as per your description but still problem is not being solved. 

Please guide me, after setup in nuxt.config and added file in plugin folder. lets say i want to use in index component the how to set and get store commit?

**Comment by dan2600** [comment]
same problem here, getting a "window is not defined error" im assuming this has something to do with SSR

**Comment by sudhir600** [comment]
@dan2600 
 let me know if you found any solution or alternative to persistence store.

**Comment by Nicolaidavies** [comment]
@sudhir600 and @dan2600 Take a look at https://github.com/robinvdvleuten/vuex-persistedstate/issues/54#issuecomment-329963248

**Comment by robinvdvleuten** [comment]
I do not use Nuxt myself so I am unable to help with that. This blog post (https://qiita.com/sakapun/items/a0cf5698751ae70c8088) is - I guess - in Chinese, but the code examples seem to be explaining Nuxt.js with my plugin.

**Comment by dan2600** [comment]
yep that fixed it. by detecting the hot reloading server side rendering it doesn't call the window function (which doesn't exists on the server side). But when it's rendering out the client it loads its correctly. 


recommend updating the read me part of this plug in from:

`// ~/plugins/localStorage.js

import createPersistedState from 'vuex-persistedstate'

export default ({store}) => {
  createPersistedState({
      key: 'yourkey',
      paths: [...]
      ...
  })(store)
}`


to 

`
// ~/plugins/localStorage.js
import createPersistedState from "vuex-persistedstate";

export default ({store, isHMR}) => {
  // In case of HMR, mutation occurs before nuxReady, so previously saved state
  // gets replaced with original state received from server. So, we've to skip HMR.
  // Also nuxtReady event fires for HMR as well, which results multiple registration of
  // vuex-persistedstate plugin
  if (isHMR) return;

  if (process.client) {
    window.onNuxtReady((nuxt) => {
      createPersistedState()(store); // vuex plugins can be connected to store, even after creation
    });
  }
};
`


@sudhir600 this should fix the problem for you too.

**Comment by syffs** [comment]
I think `onNuxtReady` is not the best hook to rehydrate the store state as it happens quite late in the nuxt client rendering flow.

I ended up defining the related plugin this way as it solves a most of issues:
```
export default ({store, isHMR, app}) => {
  if (isHMR) return

  if (!app.mixins) {
    app.mixins = []
  }

  // add persisted state as a vue created() mixin
  app.mixins.push({created () {
    createPersistedState({
      key: 'yourkey',
      paths: [...]
      ...
    })(store)
  }})
}
```

**Comment by sudhir600** [comment]
@syffs  I am still not sure how to use this.
lets say i have a store variable  cartAmnt, cartDetails,

initially, it will be null and after some action, it will be added some value. 
Now let's say user refresh the page, the only store knows that how many variables were defined.  
then how i will add key name in reatePersistedState({.. })

**Comment by syffs** [comment]
@sudhir600 I'm not sure what you mean, but if your point is that you don't know which state should be rehydrated, then it's not really a problem...

- use nuxt store in [module mode](https://nuxtjs.org/guide/vuex-store/) with whatever module name (let's say `cart`)

- set `plugins/vuex-persisted.js` [as indicated](https://github.com/robinvdvleuten/vuex-persistedstate/issues/137#issuecomment-387336440) setting the module name as `path`

```
import createPersistedState from 'vuex-persistedstate'
import Cookies from 'js-cookie'

export default ({store, isHMR, app}) => {
  if (isHMR) return
  // add persisted state as a vue created mixin
  if (!app.mixins) {
    app.mixins = []
  }
  app.mixins.push({created () {
    createPersistedState({
      key: 'someKey',
      paths: ['cart'],
      storage: {
        getItem: key => Cookies.get(key),
        setItem: (key, value) => Cookies.set(key, value, {expires: 3}),
        removeItem: key => Cookies.remove(key)
      }
    })(store)
  }})
}
```

- add the plugin in your `nuxt.config.js`

```
plugins: [{ src: '~/plugins/vuex-persisted', ssr: false }]
```

**Comment by robinvdvleuten** [comment]
I am gonna close this for now as it is not an issue with the plugin but a question about someone's application architecture. Please move the discussion to a platform like Spectrum or StackOverflow.
