### ISSUE TITLE
feature request skip frozen objects

### ISSUE THREAD

**Issue by panitaxx** [robinvdvleuten/vuex-persistedstate#139]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

persist frozen objects

**What is the expected behavior?**

would like to skip frozen object from state. 

**If this is a feature request, what is motivation or use case for changing the behavior?**

Usually the use case is that  frozen objects are stored but have circular dependencies or are handlers or functions.

**Comment by robinvdvleuten** [comment]
What's this frozen object doing in your state anyways?

**Comment by panitaxx** [comment]
I am using firestore (firebase hosted db) and in the store I store some data  which I want reactive and some  doc references (a handler for a document in the db)  which I don't want reactive because the reactivity getter and setters messes with the handlers. In vuex and in vue in general frozen objects are leaved alone.
