### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by JoeDawson** [robinvdvleuten/vuex-persistedstate#14]
Hey,

Thank you for this package, I'm looking forward to digging in.

First question, Is it possible to use this without storing them under one global key? And have them under separate keys?

The reason for this is that I have an existing application where users have info stored in a few different localStorage keys.

_Or would you suggest migrating this information into a single key?_

~Secondly, is there a way that when a user first loads my app - the data that's already in localStorage is then sync with my store? Can this be done using `getState`?~

I hope you can help.

Thanks

**Comment by JoeDawson** [comment]
You can ignore my second question, having dug into it - I can see that the data from `localStorage` is available in the store when the app gets loaded.

Just my first question I'm still not sure of really, thanks.

**Comment by robinvdvleuten** [comment]
Hi @JoeDawson! To answer your first question, if you need multiple root keys, you can initialise the plugin multiple times where each instance has a different key and different paths.

**Comment by robinvdvleuten** [comment]
Something like this;

```js
const store = new Vuex.Store({
  plugins: [
    createPersistedState({ key: 'foo', paths: ['foo.reducer.path'] }),
    createPersistedState({ key: 'bar', paths: ['bar.reducer.path'] })
  ]
})
```

**Comment by JoeDawson** [comment]
Awesome, thanks so much @robinvdvleuten. Appreciate your help.

**Comment by imShara** [comment]
Why not to use it by default? Multiple state is acceptable if you want 2-3 PersistedStates. But what if you want more?

E.g. 
You have options state with multiple options. 
User want to change options separately.

Bad solutions:
You may create one PersistedState for all options and rewrite all options on each change.
Make PersistedState for each option wich will create a lot's of listeners.

Good solution:
Use prefixed keys in PersistedState like `options.red = 128`, `options.green = 255` instead `options = JSON.stringify({red: 128, green: 255})`
