### ISSUE TITLE
Integration with nuxt not works 100%

### ISSUE THREAD

**Issue by furyscript** [robinvdvleuten/vuex-persistedstate#143]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I integrate the plugin with `nuxt`
Like this and it's work well
```
import createPersistedState from 'vuex-persistedstate'
import * as Cookies from 'js-cookie'
import cookie from 'cookie'

export default ({store, req, isDev}) => {
  createPersistedState({
    key: 'mykey',
    paths: ['auth.token'],
    storage: {
      getItem: (key) => {
        return process.client ? Cookies.getJSON(key) : cookie.parse(req.headers.cookie||'')[key]
      },
      setItem: (key, value) => Cookies.set(key, value, { expires: 365, secure: !isDev }),
      removeItem: (key) => {
        console.log('remove', key)
        return Cookies.remove(key)
      }
    }
  })(store)
}
```
The problem is that when I dispatch a store `action` into `fetch` method of nuxt (server side function) like this:
```
  logoutAndLogin ({ commit, state }) {
    commit(AuthType.LOGOUT)
    console.log('token', state.auth.token)
    //sharedService.router.replace({ path: '/login' })
    sharedService.redirect( '/login' )
  },
```
The `redirect` method is same as `context` of nuxt so a server side redirect.
It works because token will be reset and redirect go to login, but when I put a console log of token into login is set. Also into Cookie is set.
See console output
```
@action dispatch name: logoutAndLogin
token 
  nuxt:render Data fetching /account/dashboard: 15ms +0ms
  nuxt:render Rendering url /login +159ms
tokenIntoLoginPage eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE1MjgxMDc5MDF9.0zc_ohjfvma4jXvwd1I_NN3vMsAxKfxVOyquqZdm7uI

```
As you can see `token <>` is empty because commit work, after redirect the console login into login page print the token. And also my token in Cookie is set and not removed.

I think this is a bug of this package because nuxt doesn't have problem on store, only if I save into persistedstate.

**Comment by robinvdvleuten** [comment]
Can you please provide a sandbox where this issue is reproducable? It looks like an issue with your code, not this plugin.

**Comment by furyscript** [comment]
Yes this is a repo reproduction: https://github.com/furyscript/nuxt-redirect-error

You need to login, go to inspire page and make sure the first http call is a 200 request. After that try to refresh page (F5 into /inspire) until the http call return a 401 error, so you see that you return to home and not in login page.

**Comment by robinvdvleuten** [comment]
Yeah I see, this is not an issue with this plugin but with your app / nuxt setup. Please move this question to a related forum or stackoverflow.
