### ISSUE TITLE
Add a blacklist of properties that doesn't need to be saved on localStorage

### ISSUE THREAD

**Issue by waghcwb** [robinvdvleuten/vuex-persistedstate#145]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
we can make a whitelist of properties that we want to save on `localStorage` with the `paths` config

**What is the expected behavior?**
make a blacklist of properties that doesn't need to be saved on `localStorage`

**If this is a feature request, what is motivation or use case for changing the behavior?**
ignore unneeded properties of `state.js`

**Comment by waghcwb** [comment]
Sorry, I didn't realize that i can do this with `reducer` function

```js
plugins: [
  CreatePersistedState({
    key: 'vivo',
    storage: window.sessionStorage,

    reducer: (persistedState) => {
      const stateFilter = Object.assign({}, persistedState)

      delete stateFilter.modal

      return stateFilter
    }
  })
]
```

**Comment by waghcwb** [comment]
Sorry, I didn't realize that i can do this with `reducer` function

```js
import CreatePersistedState from 'vuex-persistedstate'

...

plugins: [
  CreatePersistedState({
    reducer: (persistedState) => {
      const stateFilter = Object.assign({}, persistedState)

      delete stateFilter.modal

      return stateFilter
    }
  })
]
```

**Comment by robinvdvleuten** [comment]
No problem, that's exactly the purpose of the reducer function!

**Comment by Nikey646** [comment]
For anyone who stumbles across the code posted by @waghcwb above, be careful. Using this code deletes items from your main vuex store itself. This effectively means that every time the reducer is ran, it will remove the values directly from the store...

**Comment by jaisondavis** [comment]
paths: Object.keys(state).filter(m=>m!=="the_key_you_need_blacklisted")
