### ISSUE TITLE
JSON.stringify cannot serialize cyclic structures.

### ISSUE THREAD

**Issue by sweebee** [robinvdvleuten/vuex-persistedstate#146]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I'm getting ```JSON.stringify cannot serialize cyclic structures.``` on mutations

**If the current behavior is a bug, please provide the steps to reproduce.**

```
export default new Vuex.Store({
  plugins: [createPersistedState()],
  state: {
    user: null,
    events: null,
    organisation: null,
    token: null
  },
  mutations: {
    setUser: function(data){
      this.state.user = data;
    },
    setToken: function(data){
      this.state.token = data;
    },
    setOrganisation: function(data){
      this.state.organisation = data;
    },
    setEvents: function(data){
      this.state.events = data;
    },
  },
})
```

**Comment by robinvdvleuten** [comment]
This looks more like a bug in your application's code than with this plugin. Please check if you're not serializing nested references to other objects or itself.

**Comment by Jerome1337** [comment]
I have exactly the same problem and only when I use `vuex-persistedstate`. If I remove it Vuex and everything in my app is working well.

This error is returned at every `$store.commit` or `emit` with an object payload.

For example this piece of code give this error

```
this.$emit('domainAdded', {
  name: this.domain.toLowerCase(),
  totalSent: 0,
  totalBounce: 0,
  totalComplain: 0,
  status: 0,
});
```

I don't know what in this piece of code can produce a cyclic structure.
