### ISSUE TITLE
Firefox might throw NS_ERROR_FILE_NO_DEVICE_SPACE

### ISSUE THREAD

**Issue by rodneyrehm** [robinvdvleuten/vuex-persistedstate#147]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Unhandled error `NS_ERROR_FILE_NO_DEVICE_SPACE` is thrown if there's not enough storage capacity for whatever [storage.setItem](https://github.com/robinvdvleuten/vuex-persistedstate/blob/master/index.js#L34) is supposed to write to localStorage.

**If the current behavior is a bug, please provide the steps to reproduce.**

No idea, maybe move Firefox profile to a really small volume?

**What is the expected behavior?**

No idea, failing silently isn't a good idea either

---

I've seen this being reported on a single device, so it's probably not the most urgent of problems.

**Comment by robinvdvleuten** [comment]
Why is this a bug for this plugin? It looks more like either a problem with the amount of data you want to store or a problem with your disk size.

**Comment by rodneyrehm** [comment]
It's a problem because I can't handle the error if I'm using `{ storage: window.sessionStorage }`. Of course I can wrap the methods and provide a custom storage adapter - just not sure that's the best way to go about this…

**Comment by robinvdvleuten** [comment]
What about:

```js
const createPluginWithTryCatchHandler = options => {
  try {
    return createPersistedStatePlugin(options)
  } catch (err) {
    // NS_ERROR_FILE_NO_DEVICE_SPACE...
  }
}
```

I think that's a very valid pattern to use. Or you can just set setState/getState with try/catch handlers as described in the [customize-storage](https://github.com/robinvdvleuten/vuex-persistedstate#customize-storage) example.

**Comment by rodneyrehm** [comment]
I'm not sure how `createPluginWithTryCatchHandler` would even catch that error, since it's not necessarily thrown during execution of `createPersistedStatePlugin()` but on state change.

> Or you can just set setState/getState with try/catch handlers as described in the customize-storage example.

allow me to quote MDN on [setItem()](https://developer.mozilla.org/en-US/docs/Web/API/Storage/setItem):

> setItem() may throw an exception if the storage is full. Particularly, in Mobile Safari (since iOS 5) it always throws when the user enters private mode (Safari sets quota to 0 bytes in private mode, contrary to other browsers, who allow storage in private mode, using separate data containers). Hence developers should make sure to **always catch the possible exceptions from setItem()**.

Is it really the best course of action to make anyone using `vuex-persistedstate` take care of this themselves?

**Comment by kculmback** [comment]
I had a similar issue with users using Microsoft Edge. It seems that it has a bug that will greatly reduce the amount of localstorage a site is allowed to have. I came up with a 'fallback' state option that seems to work pretty well. Here's the solution:
```
// set up fallbackState object
const fallbackState = {
  useFallback: false
}

const root = {

  strict: true,

  plugins: [createPersistedState({
    getState: (key, storage, value) => {
      // check to see if useFallback is set to true,
      // if it is, return the state for that key
      if (fallbackState.useFallback) {
        return fallbackState[key]
      }
      try {
        return (value = storage.getItem(key)) && typeof value !== 'undefined'
          ? JSON.parse(value)
          : undefined
      } catch (err) { }

      return undefined
    },
    setState: (key, state, storage) => {
      try {
        // set useFallback to false if we succeed in setting state in storage
        fallbackState.useFallback = false
        return storage.setItem(key, JSON.stringify(state))
      } catch (e) {
        // if we fail, set the state to the key in the fallbackState object
        // and set useFallback to true
        fallbackState[key] = state
        fallbackState.useFallback = true
      }
    }
  })],

  ...
}
```

If anyone has any suggestions on how this could be improved, let me know!
