### ISSUE TITLE
Prevent race condition with mutex?

### ISSUE THREAD

**Issue by dcvice1967** [robinvdvleuten/vuex-persistedstate#149]
**Do you want to request a *feature* or report a *bug*?**  Feature

**What is the current behavior?** Does this module use some sort of mutex to lock the state prior to making changes? 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?** 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by robinvdvleuten** [comment]
No this does not have some sort of mutex built-in and such functionality is out of scope for the plugin.
