### ISSUE TITLE
Restoring state for dynamically registered modules

### ISSUE THREAD

**Issue by vividvilla** [robinvdvleuten/vuex-persistedstate#15]
I noticed that when the modules are registered dynamically it doesn't restore the state persisted in localstorage. I have an empty store which initialized with this plugin and modules are registered dynamically after that. 

Is there any way to overcome this limitation?

**Comment by robinvdvleuten** [comment]
@vividvilla what do you mean with dynamically registered modules? Can you give a small code example?

**Comment by vividvilla** [comment]
I have initialized an empty store something like this  (`store.js`)

```
import Vue from "vue"
import Vuex from "vuex"
import createPersistedState from "vuex-persistedstate"

Vue.use(Vuex)

export default new Vuex.Store({
	modules: {},
	plugins: [createPersistedState({
		key: "store",
		getState: key => { console.log(key) }
	})]
})
```

I have several [vue js plugins](https://vuejs.org/v2/guide/plugins.html) which are logically separated and has it own stores (`store.js` inside modules) which are registered as modules to vuex store dynamically when App is loaded. For example my `main.js` file looks something like this
```
import store from "./store"
Vue.use(User, {"store": store})
```

User vue plugin registers its store as a vuex module. Here is an example

```
// Inside User module
import store from "./store"

User.install = function (Vue, options) {
	if (options.store) {
		options.store.registerModule("user", store)
	}
}
```

When all the modules are registered and if any state is mutated it's getting stored in localstorage but when app reloads it's not restoring the Vuex store from localstorage.

**Comment by robinvdvleuten** [comment]
Is it an idea to register the vuex-persistedstate plugin per module then? You can register it multiple times with the same (default) key but with different paths

**Comment by vividvilla** [comment]
Is it possible to register plugins also dynamically in Vuex just like the modules? I don't see any API for that in Vuex docs.

**Comment by robinvdvleuten** [comment]
Ok that's indeed not possible. I am not using any vuex / vue plugin combinations, only the `vuex-router-sync` module. I am sorry that I cannot help you any further as it seems an internal vuex thing.
