### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by AlexeyTcapaev** [robinvdvleuten/vuex-persistedstate#152]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
i try to push object in array but have this error 'Converting circular structure to JSON',i check your closed issues and find some for it, and try to add a static value ,for example - let a = 123;
and i got again this errpr

**If the current behavior is a bug, please provide the steps to reproduce.**
in some component ;
 let temp = 1234;
      this.AddProduct(temp);
in store :             state.products.push()
and that all

**What is the expected behavior?**
added a this variable into array
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by robinvdvleuten** [comment]
@AlexeyTcapaev this sounds like an issue with your application, not this plugin. Please do not try to serialize any references to objects in your JSON to prevent this.

**Comment by robinvdvleuten** [comment]
@AlexeyTcapaev I do think so, otherwise come up with a reproducible codesandbox and reopen this issue as I do not have the time to delve into this myself.

**Comment by TitanFighter** [comment]
In my case I had `Converting circular structure to JSON` caused by an event listener on `resize`. It seems to many values in a short period of time were provided, so I fixed it using `Vue.nextTick`

**Comment by itsbibsbarreto** [comment]
Guys, I was having this error, I was importing the lib like that:

`plugins: [createPersistedState()],`

I changed to: 

`plugins: [createPersistedState],`

and it worked!!

**Comment by sermo-de-arboribus** [comment]
Bianca, it seems with this "trick" it won't update the local storage anymore, so that didn't work for me.

I debugged my application by setting a breakpoint in the module's setState function and found the offending object that could not be serialized to JSON. In my case some of my objects had references to "parent" objects that I could remove. If that's not an option for you, you can try to workaround like this: https://stackoverflow.com/questions/11616630/json-stringify-avoid-typeerror-converting-circular-structure-to-json

**Comment by itsbibsbarreto** [comment]
@sermo-de-arboribus this is weird, because this bug that you said happened to me when I was importing with the parentheses. Try to uninstall and install it again, maybe it will work like it happened to me. I didn't have to do a workaround.

**Comment by zerotower69** [comment]
> Guys, I was having this error, I was importing the lib like that:
> 
> `plugins: [createPersistedState()],`
> 
> I changed to:
> 
> `plugins: [createPersistedState],`
> 
> and it worked!!

well, it works on my project! You know why? I really want to know.
