### ISSUE TITLE
Persisted state does not persist on page reload

### ISSUE THREAD

**Issue by ekreutzer** [robinvdvleuten/vuex-persistedstate#153]
**Do you want to request a *feature* or report a *bug*?**
Report a *bug*.

**What is the current behavior?**
Using Firebase for user authentication along with Vue (obviously). I have the persisted state setup in my `store.js`, which is below:

`plugins: [
		createPersistedState({
			getState: (key) => Cookies.getJSON(key),
			setState: (key, state) => Cookies.set(key, state, { expires: 3, secure: false })
		})
	]
`
On reload, all of the conditionally-rendered components which depend on an auth token are not rendered; I imagine that either the cookie cannot be fetched or it is deleted at some point. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Using the `createPersistedState` plugin in my `store.js`, login in to user's account, reload the page. All components dependent on an auth token are no longer visiblbe. 

**What is the expected behavior?**
It should maintain the cookie and user auth token to be fetched upon page reload.

**Comment by lbineau** [comment]
The first step is to know if the cookie is set. I had the same issue but it was simply I used `secure: true` with HTTP protocol or `secure: false` with HTTPS protocol so the cookie wasn't set.
<img width="838" alt="vuex-persistedstate with js-cookie - codesandbox 2018-08-07 10-03-41" src="https://user-images.githubusercontent.com/1534688/43762915-8fb84b1e-9a29-11e8-9f56-3042f4e9d359.png">

**Comment by robinvdvleuten** [comment]
Looks more like a bug with your codebase than with this plugin. Please provide a runnable codesandbox or jsfiddle to prove otherwise.

**Comment by dennernavarro** [comment]
> The first step is to know if the cookie is set. I had the same issue but it was simply I used `secure: true` with HTTP protocol or `secure: false` with HTTPS protocol so the cookie wasn't set.
> <img alt="vuex-persistedstate with js-cookie - codesandbox 2018-08-07 10-03-41" width="838" src="https://user-images.githubusercontent.com/1534688/43762915-8fb84b1e-9a29-11e8-9f56-3042f4e9d359.png">

Your solution worked well! Thank you!

**Comment by eeerrrttty** [comment]
I'm also with the same bug.

When using cookies just. other storages do not bug.
