### ISSUE TITLE
IE 11 and Vue Cli 3

### ISSUE THREAD

**Issue by savenko** [robinvdvleuten/vuex-persistedstate#154]
Hello!
I use Vue Cli 3 with TypeScript
For this i create file:

import Vue from 'vue';
import Vuex from 'vuex';
import createPersistedState from 'vuex-persistedstate';

Vue.use(Vuex);

export default new Vuex.Store({
    plugins: [createPersistedState({
        storage: window.sessionStorage,
    })],
    modules: {
        ...
    },
    mutations: {
        
    },
    actions: {},
});

In IE 11 i see error invalid storage instance given

**Comment by robinvdvleuten** [comment]
Please check the issue template: 

```
If you try to report a bug but do not not provide a reproducible codesandbox or fiddle, 
the issue will be closed without further notice.
```
