### ISSUE TITLE
Prevent persisted state locking up app in VueX

### ISSUE THREAD

**Issue by modermo** [robinvdvleuten/vuex-persistedstate#157]
Posted this over in SO, but thought it might also be useful to ask here.

I'm using this module to keep track of my state and persist it to `localStorage`. The problem is that due to the amount of `state` that needs to be saved, the app gets locked up every time an update to my data occurs.

In order to solve that, I'm trying to use a `promise` to allow business calculations to be performed whilst the string is being generated. Once the string is ready, it should then be `set` to `localStorage`.

This is what I have:

```
const buildLocalStorageString = async (state) => {
  return await JSON.stringify(state);
}

export default new Vuex.Store({
  state: { etc, etc, etc },

  plugins: [createPersistedState({
    key: 'myApp',
    setState (key, state, storage) {
      buildLocalStorageString(state).then(string => {
        storage.setItem(key, string) 
      }) 
    }
  })],
})

```
Problem is, it doesn't solve the problem. There is still a noticeable delay when the app updates.

**Comment by robinvdvleuten** [comment]
That is because `JSON.stringify()` is not an asynchronous function, so it will block while computing. And using promises to write to storage is not working due to Vuex's synchronous nature, that's why this plugin also doesn't support things like LocalForage.
