### ISSUE TITLE
Please use async api to compatible localforage

### ISSUE THREAD

**Issue by fsx950223** [robinvdvleuten/vuex-persistedstate#158]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
can't use localforage
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
can use localforage as storage
**If this is a feature request, what is motivation or use case for changing the behavior?**
If this package use async api,it will compatible localforage and make no effect with localstorage

**Comment by robinvdvleuten** [comment]
Please see #22
