### ISSUE TITLE
Example needed 

### ISSUE THREAD

**Issue by martinrisseeuw** [robinvdvleuten/vuex-persistedstate#16]
I am trying to implement vuex-persistedstate but I don't understand how to update the state in the local storage.

```
import Vuex from 'vuex'
import createPersistedState from 'vuex-persistedstate'
import * as Cookies from 'js-cookie'

const store = new Vuex.Store({
  plugins: [
    createPersistedState({
      getState: (key) => Cookies.getJSON(key),
      setState: (key, state) => Cookies.set(key, state, { expires: 3, secure: true })
    })
  ],
  state: {
    counter: 0,
    showLogin: false,
    loggedIn: false,
    showIntro: true
  },
  mutations: {
    toggleLogin (state) {
      state.showLogin = !state.showLogin
    },
    toggleIntro (state) {
      state.showIntro = !state.showIntro
    }
  }
})
export default store
```

This is the code I have at this moment. I do see that a local storage is added in my web inspector but unfortunately it's not updated when I trigger a state mutation. How should I trigger the mutation to also update the local storage?

**Comment by robinvdvleuten** [comment]
@martinrisseeuw you are not setting the localstorage, you are overriding the default with a "cookie" storage. Could you please try the bare [usage example](https://github.com/robinvdvleuten/vuex-persistedstate#usage) and see if that works?

**Comment by martinrisseeuw** [comment]
It doesn't seem to work for me. 

This is the code I have at this moment:
```
import Vuex from 'vuex'
import createPersistedState from 'vuex-persistedstate'

const store = new Vuex.Store({
  state: {
    counter: 0,
    showLogin: false,
    loggedIn: false,
    showIntro: true
  },
  mutations: {
    toggleLogin (state) {
      state.showLogin = !state.showLogin
    },
    toggleIntro (state) {
      state.showIntro = !state.showIntro
    }
  },
  plugins: [createPersistedState()]
})
export default store
```

Here you can see that it does create a row in the localstorage:
![image](https://cloud.githubusercontent.com/assets/8780559/24466073/d30d5d2e-14af-11e7-9a3a-96634c0c4aa7.png)

When I call a mutation it doesn't update the localstorage unfortunately.

**Comment by robinvdvleuten** [comment]
@martinrisseeuw can you please point me to an example repo with your setup so I can try it myself?

**Comment by martinrisseeuw** [comment]
@robinvdvleuten I added you my repo as a collaborator for now. It's a Nuxt.js project https://nuxtjs.org/

**Comment by robinvdvleuten** [comment]
@martinrisseeuw I ran your application locally and it looks like the state is overwritten by the initial state on boot. I'll investigate it somewhat further tomorrow.

**Comment by martinrisseeuw** [comment]
@robinvdvleuten thanks. For more info about nuxt.js you can check out the documentation on their site: nuxtjs.org

**Comment by robinvdvleuten** [comment]
@martinrisseeuw so I created my own setup of nuxt.js with vuex here => https://github.com/robinvdvleuten/vuex-persistedstate. I see that all actions are reflected in the local storage, but on reloading the store is on it's initial state instead of the persisted. 
It looks like Nuxt.js is hooking in on this hydration (https://nuxtjs.org/guide/vuex-store/#the-nuxtserverinit-action), as I see that the store is correctly replaced by my module but afterwards it's on its initial state again. Maybe it's an idea to move this issue to the Nuxt.js repo?

**Comment by robinvdvleuten** [comment]
@martinrisseeuw ah I now discovered the issue. If you look at the generated index.js file, you'll see the following line;

```js
// Replace store state before calling plugins
if (window.__NUXT__ && window.__NUXT__.state) {
  store.replaceState(window.__NUXT__.state)
}
```

This `replaceState` is called after the call of the `vuex-persistedstate` plugin, so the hydrated store is replaced with the data received from the server (through index.html). This is an issue with the SSR setup (handled by Nuxt) and not with this plugin.

**Comment by martinrisseeuw** [comment]
Okay I will research how to fix this. Thanks for the help.
