### ISSUE TITLE
An error occurred after using vue-cli3 under IE9&10

### ISSUE THREAD

**Issue by HenryYong** [robinvdvleuten/vuex-persistedstate#165]
**Do you want to request a *feature* or report a *bug*?**
Yes
**What is the current behavior?**
![image](https://user-images.githubusercontent.com/7967105/45916323-8fb25100-be96-11e8-9fe4-fc18b723b251.png)

According to codes which I marked by underline: `throw new Error("Invalid storage instance given");`,
I found that it's belongs to `vuex-persistedstate`. But I cannot figure out the reason by the error thrown by IE, and the error says there is a syntax error. Pls let me know if more info is needed. THX!

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by robinvdvleuten** [comment]
This is not a bug with the plugin itself. Anything below IE11 does not have support for local storage (https://caniuse.com/#search=local%20storage). You are also using untranspiled code to the browser (that's your syntax issue). So no bug with this plugin but more an issue with your setup.

**Comment by HenryYong** [comment]
Thx a lot...
