### ISSUE TITLE
Feature: rehydrated callback

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [robinvdvleuten/vuex-persistedstate#166]
**Do you want to request a *feature* or report a *bug*?** feature

**What is the current behavior?** currently it is hard to tell when a store was rehydrated. This makes re-initilisations of stateful JS libraries and classes very hard. 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?** rehydrated () { /* do something */ }

**If this is a feature request, what is motivation or use case for changing the behavior?**

 A good example for this is `axios`. Axios allows to set default headers, like `Authorization` during development or page refresh a user would expect that header to be rehydrated. Which is hard to achieve or inherently racy for components. The rehydrate callback could take an implementation for that.

Thanks for considering.

**Comment by imShara** [comment]
That! I was surprized when found that vuex-persistedstate rehydrates asyncronously. That's thing makes this lib useless at all to store application options.

**Comment by rfox12** [comment]
@imShara if you use the `fetchBeforeUse` option, doesn't that make your app options available ASAP?

**Comment by jaythomas** [comment]
@rfox12 `fetchBeforeUse: true` makes no difference as it doesn't affect load time, just load order. In fact, load times are completely relying on Nuxt's async store initialization which can be slow. Regarding the feature request at hand, I see the `rehydrated` callback was added a year ago though so @robinvdvleuten can probably close this issue.

**Comment by robinvdvleuten** [comment]
Thank you for figuring this out @jaythomas
