### ISSUE TITLE
State is not immediately loaded into the store

### ISSUE THREAD

**Issue by victor192** [robinvdvleuten/vuex-persistedstate#167]
And use `vuex-persistedstate` plugin in Nuxt together with `js-cookies`. I noticed such a thing that when the page loads, the properties from state are not immediately initialized from cookies, but only after the page is fully loaded. It turns out that first the value of state is taken as from the store, and then replaced by the value of cookies. Is it possible to follow so that the values in the state are immediately initialized from cookies?

**Comment by Jesus82** [comment]
Same happens under Nuxt using `localStorage`.

**Comment by RN3r1** [comment]
I have the same issue, does anybody have a workaround?

**Comment by woodgates** [comment]
Same problem here. Local storage persist on the client only. When you go to NUXT the store is as its default configuration. This makes the plugin unuseful with NUXT.

I guess there should be a workaround with nuxtServerInit, if anyone can help.

@victor192  I suggest to put 'nuxt' in the subject.

**Comment by Jesus82** [comment]
@woodgates I can use it with Nuxt with the following configuration, the only problem is that there is always a less than 1s lapse until LocalStorage is loaded (at least in my case). My configuration is:

_plugin/persitedstate.js_
```

import createPersistedState from 'vuex-persistedstate'

export default ({store, isHMR}) => {

  if (isHMR) return;

  if (process.client) {
    window.onNuxtReady((nuxt) => {
      createPersistedState({
        paths: ['myVariableInLocalStorage','myAnotherVariableInLocalStorage'],
      })(store); 
    });
  }
}
```

_nuxt.config.js_

_plugins: [
    { src: '~/plugins/vuex-persistedstate', ssr: false },
]_

**Comment by woodgates** [comment]
@Jesus82 
Thanks! It works great, the delay is not an issue to UX I think.

**Comment by woodgates** [comment]
@Jesus82 
Hi. Although the solution works it still has a problem. The vue-router middleware is loaded before the persist plugin, so, when the middleware is executed the store is empty. This is an issue if you are managing user logins with Store.

**Comment by moifort** [comment]
I have the same issue, is because you used `window.onNuxtReady`. If you want to load immediately write your plugin like below:

```javascript
import createPersistedState from 'vuex-persistedstate'

export default ({store}) => createPersistedState({})(store)
```

**Comment by robinvdvleuten** [comment]
This plugin was never meant to be used with Nuxt.js, so I am gonna close this for now. Please move to a appropiate support channel like StackOverflow.

**Comment by Petercopter** [comment]
@moifort That works! Right...? It seems to be working...

**Comment by jcjp** [comment]
I think the solution to this problem is to set `fetchBeforeUse` to true based on the `README` file. `fetchBeforeUse` `<Boolean>`: A boolean indicating if the state should be fetched from storage before the plugin is used. Defaults to `false`.
