### ISSUE TITLE
It doesn't work in store with different modules

### ISSUE THREAD

**Issue by deanilvincent** [robinvdvleuten/vuex-persistedstate#169]
Good day,

I just installed this package on my project.

My scenario is, I have store folder and inside that store folder, I have 1 folder with a name of `modules` and a file `store.js` where it has instatiation of `Vuex.Store` inside.

![storefolder](https://user-images.githubusercontent.com/10904957/47350177-dc808600-d6e7-11e8-8165-04421acd60b8.PNG)

Inside the `modules` has multiple .js files.

My `store.js` looks like this with `createPersistedState` inside but it doesn't work:

    import Vue from 'vue'
    import Vuex from 'vuex'

    import module1 from './modules/module1'
    import module2 from './modules/module2'
    import module3 from './modules/module3'

    // import state persistent
    import createPersistedState from 'vuex-persistedstate';
    
    Vue.use(Vuex);

    const store = new Vuex.Store({
        modules: {
             module1, module2, module3
        },
        plugins: [createPersistedState()]
    });

    export default store;

The version that I'm using is: `^2.5.4`

Thank you in advance.

**Comment by valeriancure** [comment]
try :
````
const persistedPaths = ['module1', 'module2', 'module3']
...
plugins: [
    createPersistedState({ paths: persistedPaths })
  ]
````

**Comment by deanilvincent** [comment]
@valeriancure it doesn't work either.

**Comment by CarlKlein** [comment]
Hi,

My setup is basically the same and I don't have the issue. Only difference is how I include the modules in the store:
```
const store = new Vuex.Store({
        modules: {
            module1: module1,
            module2: module2,
            module3: module3,
        },
        plugins: [createPersistedState({
            key: 'MYAPP'
        })]
    });
```

**Comment by jhonja93** [comment]
Hi,

I have the same configuration as @CarlKlein, what happens if I have nested modules, how do I prevent these modules from persisting?

**Comment by AlexNikonov** [comment]
Try to remove 'paths' parameter at all. In my case it solved issue.

**Comment by enbermudas** [comment]
None of this two solutions is working for me. I don't know what else can I do.

**Comment by oimou** [comment]
It works for me. This might help you find out the cause.
https://codesandbox.io/s/vuex-persistedstate-mh9ge

**Comment by matinjugou** [comment]
I guess this problem is because of the namespace, which VUEX's developers have already mentioned in their documentation: [caveat-for-plugin-developers](https://vuex.vuejs.org/guide/modules.html#caveat-for-plugin-developers)
The solution is easy: use plugin in every submodule instead of the root one. like this:

**Comment by sanderyt** [comment]
> It works for me. This might help you find out the cause.
> https://codesandbox.io/s/vuex-persistedstate-mh9ge

This solved it for me.

**Comment by thekubilay** [comment]
> > It works for me. This might help you find out the cause.
> > [codesandbox.io/s/vuex-persistedstate-mh9ge](https://codesandbox.io/s/vuex-persistedstate-mh9ge)
> 
> This solved it for me.

it's helped a lot. thank you for the sandbox also...

**Comment by l619534951** [comment]
> > > 这个对我有用。这可以帮助您找出原因。
> > > [codeandbox.io/s/vuex-persistedstate-mh9ge](https://codesandbox.io/s/vuex-persistedstate-mh9ge)
> > 
> > 
> > 这为我解决了。
> 
> 它很有帮助。谢谢你的沙箱...

I also encountered this problem, how did you solve it ?, the page is 404, could you help me ?

**Comment by l619534951** [comment]
> > > It works for me. This might help you find out the cause.
> > > [codesandbox.io/s/vuex-persistedstate-mh9ge](https://codesandbox.io/s/vuex-persistedstate-mh9ge)
> > 
> > 
> > This solved it for me.
> 
> it helped a lot. thank you for the sandbox also...

I also encountered this problem, how did you solve it ?, the page is 404, could you help me ?

**Comment by thekubilay** [comment]
> > > > 这个对我有用。这可以帮助您找出原因。
> > > > [codeandbox.io/s/vuex-persistedstate-mh9ge](https://codesandbox.io/s/vuex-persistedstate-mh9ge)
> > > 
> > > 
> > > 这为我解决了。
> > 
> > 
> > 它很有帮助。谢谢你的沙箱...
> 
> I also encountered this problem, how did you solve it ?, the page is 404, could you help me ?

it's bad news the page is 404. 
but you can get a idea from my code. 
here is the example of usage:

```
import {asana} from "../src/stores/asana";
import {database} from "../src/stores/database";
import {globals} from "../src/stores/globals";

Vue.use(Vuex)

export default new Vuex.Store({
	modules: {
		asana,
		database,
		globals,
	},
	plugins: [
		createPersistedState({
			paths: ["database.presanceAsana", "globals.visiblePage", "globals.activeTab",]
		})
	]

})
```

paths is array that contains modules and it's states. for example I have a module that named `database` and it has `state` that named `presanceAsana` 

I hope it helps...

**Comment by l619534951** [comment]
> for example I have a module that named

I had already try that, but it's not work, did you use namespace options in the state ?

**Comment by thekubilay** [comment]
nope I didn't, no need to use namespace in the state. what's ur error exactly?

**Comment by thekubilay** [comment]
> > for example I have a module that named
> 
> I had already try that, but it's not work, did you use namespace options in the state ?

nope I didn't, no need to use namespace in the state. what's ur error exactly?

**Comment by l619534951** [comment]
> nope I didn't, no need to use namespace in the state. what's ur error exactly?
The

> > > for example I have a module that named
> > 
> > 
> > I had already try that, but it's not work, did you use namespace options in the state ?
> 
> nope I didn't, no need to use namespace in the state. what's ur error exactly?

The state is not persisted to localstore...
![image](https://user-images.githubusercontent.com/17621099/75624130-96490a00-5bec-11ea-875b-f07c9b6ae4a1.png)

**Comment by thekubilay** [comment]
> The state is not persisted to localstore...

you are pretty much using it wrong, that's why. 

here try it like below. 

```
plugins: [
	createPersistedState({
		paths: ["user.yourStateName,]
	})
]

```

when you import the module. Let's say in your case this is your `user` module. Use it in the paths array like above. And after that write the `.yourStateName` which state you want to store in the localStorage.

by the way. your should import your modules inside the curly bracket {user}, {settings}

**Comment by l619534951** [comment]
> > 状态未持久到本地存储...
> 
> 您几乎错误地使用了它，这就是原因。
> 
> 在这里尝试如下。
> 
> ```
> plugins: [
> 	createPersistedState({
> 		paths: ["user.yourStateName,]
> 	})
> ]
> ```
> 
> 导入模块时。假设您的情况是这是您的`user`模块。在上面的paths数组中使用它。然后写出`.yourStateName`要存储在localStorage中的状态。
> 
> 顺便说说。您应该将模块导入大括号{user}，{settings}中


> > The state is not persisted to localstore...
> 
> you are pretty much using it wrong, that's why.
> 
> here try it like below.
> 
> ```
> plugins: [
> 	createPersistedState({
> 		paths: ["user.yourStateName,]
> 	})
> ]
> ```
> 
> when you import the module. Let's say in your case this is your `user` module. Use it in the paths array like above. And after that write the `.yourStateName` which state you want to store in the localStorage.
> 
> by the way. your should import your modules inside the curly bracket {user}, {settings}

This is my code, Is there something mistake i made ? https://codesandbox.io/s/nice-jones-fjojt

**Comment by l619534951** [comment]
> > The state is not persisted to localstore...
> 
> you are pretty much using it wrong, that's why.
> 
> here try it like below.
> 
> ```
> plugins: [
> 	createPersistedState({
> 		paths: ["user.yourStateName,]
> 	})
> ]
> ```
> 
> when you import the module. Let's say in your case this is your `user` module. Use it in the paths array like above. And after that write the `.yourStateName` which state you want to store in the localStorage.
> 
> by the way. your should import your modules inside the curly bracket {user}, {settings}

This is my code, Is there something mistake i made ? The state is not persisted to localstore...  https://codesandbox.io/s/nice-jones-fjojt

**Comment by thekubilay** [comment]
> This is my code, Is there something mistake i made ? The state is not persisted to localstore... [codesandbox.io/s/nice-jones-fjojt](https://codesandbox.io/s/nice-jones-fjojt)

`store.js` is empty

**Comment by l619534951** [comment]
> codesandbox.io/s/nice-jones-fjojt

sorry, i had fixed that

**Comment by l619534951** [comment]
> > This is my code, Is there something mistake i made ? The state is not persisted to localstore... [codesandbox.io/s/nice-jones-fjojt](https://codesandbox.io/s/nice-jones-fjojt)
> 
> `store.js` is empty

I mean fixed `store.js is empty`, I still need your help...

**Comment by swish-swosh** [comment]
When I remove the remark from // 'components.countries my cookies persistance for the auth module doesn't work anymore. ( ie cookie persistance doesn't create the required vuex cookies when I have multiple paths to different modules )

`const dataState = createPersistedState({
  paths: [
    'auth.accessToken',
    'auth.profile',
    'auth.rememberMe',
  //  'components.countries'
  ],
  storage: {
    getItem: key => Cookies.get(key),
    setItem: (key, value) => Cookies.set(key, value, {expires: 30 }),
    removeItem: key => Cookies.remove(key)
  }
})

export default new Vuex.Store({
  plugins: [dataState],
  modules: {
    components,
    auth
  }
})`
