### ISSUE TITLE
About mechanism

### ISSUE THREAD

**Issue by hyunsooda** [robinvdvleuten/vuex-persistedstate#172]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

Hi, I am korean student.
The reason why I am writing this issue is to ask about how to store vuex state if we refresh current webpage.
if I don't give any option when I use your plugin, how does it works?
if you have a time to write comment, I will appreciate.
Thanks and have a nice day.

**Comment by robinvdvleuten** [comment]
Please check the README; it says that you can use localStorage, cookies or whatever you pleases. It uses localStorage by default.
