### ISSUE TITLE
Do not trigger setState when the module is not in `paths` config.

### ISSUE THREAD

**Issue by Yudikubota** [robinvdvleuten/vuex-persistedstate#174]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
VuexPersistedState triggers `setState` even when the module is not in `paths` config.

**What is the expected behavior?**
Only trigger `setState` when modifying a state that is being watched in `paths`

**Code**
Change the default filter or create a prefilter
```
filter(mutation) {
        for (let path of paths) {
            if (mutation.type.startsWith(path))
                return true
        }

        return false
}
```

[![Edit vuex-persistedstate](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6vxpkm6y8k)

**If this is a feature request, what is motivation or use case for changing the behavior?**
Performance improvement

**Comment by robinvdvleuten** [comment]
You could easily do this yourself with the example code you provided. I am just gonna let everything pass through by default.
