### ISSUE TITLE
some bug with reducer

### ISSUE THREAD

**Issue by chavesgu** [robinvdvleuten/vuex-persistedstate#175]
**Do you want to request a *feature* or report a *bug*?**
a bug
**What is the current behavior?**
this plugin can not save data when refresh
**If the current behavior is a bug, please provide the steps to reproduce.**
```js
createPersistedState({
      reducer(state) {
        return {
          phone: state.user.phone,
        };
      }
})
```
when refresh, the data will lossed

[https://jsfiddle.net/wmf8zvf8/131/](https://jsfiddle.net/wmf8zvf8/131/)
**What is the expected behavior?**
when i use reducer and refresh, the data will not lossed
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by robinvdvleuten** [comment]
This is not a bug with the plugin, but with your setup. Please provide more information about your setup, otherwise this issue will be closed.

**Comment by chavesgu** [comment]
> This is not a bug with the plugin, but with your setup. Please provide more information about your setup, otherwise this issue will be closed.

i only set reducer , the code is above, `state.user`is my vuex module,`state.user.phone`is key in my `user`module,  when i refresh brower, the data will be reset.    but if i don't set reducer, all data will saved, if refresh brower, all data will not be reset,  so  how to use reducer correctlly?
