### ISSUE TITLE
Question: Possibility of a 100% persistent storage?

### ISSUE THREAD

**Issue by lorro** [robinvdvleuten/vuex-persistedstate#177]
Hi,

I'm looking for a solution for my Vue app that syncs certain data from my vuex store locally.
I've tried implementations of this that use LocalStorage & IndexedDB. The problem however is that whenever the user decides to remove "cookies and other data" in the settings of chrome also this persisted data gets wiped. I would like to prevent that users can delete the synced data.

Somebody got any suggestions what kind of implementation could tackle this problem?
Is it achievable with vuex-persistedstate?

Thanks

**Comment by robinvdvleuten** [comment]
Just synchronize your state with a persistent backend would work in this case. It would be a major flaw in browsers if it's possible to create undeletable files through JS.
