### ISSUE TITLE
API for reloading state from localStorage after storage event

### ISSUE THREAD

**Issue by mp3il** [robinvdvleuten/vuex-persistedstate#180]
Hi,

I'm currently using this plugin in a chrome extenstion, where I have 2 seperate tabs (background and popup) - and I want to be able to sync changes when the background changes the state.

The way to do it is probably listening to storage event - the problem is that I don't know how to force the tab that needs to sync from localStorage to do it.

is there any API for it? for hydration ?

**Comment by mp3il** [comment]
What Iv'e ended up doing is using:

`// Listen to storage events
window.addEventListener('storage', function (e) {
  if (e.key !== 'vuex') {
    // console.log('Ignored an event: ', e)
    return
  }

  var vuexJSON = JSON.parse(localStorage['vuex'])
  store.replaceState(vuexJSON)
}, false)`

**Comment by J4si3k** [comment]
> What Iv'e ended up doing is using:
> 
> ```
> // Listen to storage events
> window.addEventListener('storage', function (e) {
>   if (e.key !== 'vuex') {
>     // console.log('Ignored an event: ', e)
>     return
>   }
> 
>   var vuexJSON = JSON.parse(localStorage['vuex'])
>   store.replaceState(vuexJSON)
> }, false)
> ```

could you add a more extended example? I'm not sure how to connect with configuration

**Comment by mp3il** [comment]
> > What Iv'e ended up doing is using:
> > ```
> > // Listen to storage events
> > window.addEventListener('storage', function (e) {
> >   if (e.key !== 'vuex') {
> >     // console.log('Ignored an event: ', e)
> >     return
> >   }
> > 
> >   var vuexJSON = JSON.parse(localStorage['vuex'])
> >   store.replaceState(vuexJSON)
> > }, false)
> > ```
> 
> could you add a more extended example? I'm not sure how to connect with configuration

You can add this code to your created () method in your parent Vue component to make sure that the window object is available. 

It's simply listen for localStorage events, and once the vuex key is changed (it's the default key for vuex-persistedstate) it will replace it with the new storage. please note that only the original window that made the localStorage events won't fire the storage event, only the other windows in the same domain.

**Comment by BevanR** [comment]
```ts
// Reload state from disk when it changes in any other tab.
// @see https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event
window.addEventListener('storage', event => {
  if (event.key === 'vuex') {
    store.replaceState(JSON.parse(localStorage.vuex))
  }
})

```

Related;

- https://github.com/robinvdvleuten/vuex-persistedstate/issues/232
- https://github.com/robinvdvleuten/vuex-persistedstate/issues/234
- https://github.com/robinvdvleuten/vuex-persistedstate/issues/180
