### ISSUE TITLE
What's the easiest way to apply a patch when a partical state is retrieved from and set to store.

### ISSUE THREAD

**Issue by paulvanbladel** [robinvdvleuten/vuex-persistedstate#183]
I hope I don't bother you with my question. If so, please simply disregard.
I'm trying to get my head around a potentially simple problem.
I'm using vuex-persistedstate with following very simple config.

```
plugins: [createPersistedState({
      storage: window.sessionStorage,
      paths: [
         'myModule.myState',
         'otherstuff'
       ]
    })],
...
```
Now I want to apply a small patch bothw when 1. the state 'myModule.myState' is stored to sessionStorage and 2. when 'myModule.myState' is retrieved. So in other words, the actual state in vuex should not be aware of the patch.
I'm not seeing from the documentation how to do this.
Thanks a lot if you can find some time to shed a light on this.

**Comment by robinvdvleuten** [comment]
Looks like you'll need to add your own `reducer` method. Please take a look at the default (https://github.com/robinvdvleuten/vuex-persistedstate/blob/master/index.js#L37).
