### ISSUE TITLE
when I open a new page, the attribute i had set in localStorage has missing

### ISSUE THREAD

**Issue by callmehui** [robinvdvleuten/vuex-persistedstate#184]
This is the first time I have raised an issue, so I hope you can take your  patience to read mu words.
I have set a state  to store an attribute(named 'to_candicate_positionid') , and I want to use this state as my default value; but when my program  have opened a new page, this state which have been set in localStorage is missing.
sure, I just need to use localStorage to store my attribute and get it from localStorage when I want to use it, and  I have done this; but I think this maybe a bug and can improve this plug-in.
thanks for your reading and your reply.

**Comment by robinvdvleuten** [comment]
Can you provide a runnable example on codesandbox?

**Comment by robinvdvleuten** [comment]
> If you try to report a bug but do not not provide a reproducible codesandbox or fiddle, the issue will be closed without further notice.
