### ISSUE TITLE
Does hydration happen automatically?

### ISSUE THREAD

**Issue by EvanAgee** [robinvdvleuten/vuex-persistedstate#185]
First off, thanks so much for the hard work!

I had a quick question, does state hydration happen automatically behind the scenes? It doesn't appear so but I wanted to verify before I manually implement it. Thanks!

**Comment by robinvdvleuten** [comment]
It should be automatically. If you provide a codesandbox of your setup, I'll look into it.

**Comment by gotexis** [comment]
Hi just starting with the package.

I believe a usual use case will be to call an API and store some data returned into vuex.

Then this package will put data into local storage.

The question is that how to load local data. I'm thinking maybe check local vuex state to see if the data is already there?

**Comment by robinvdvleuten** [comment]
What do you mean with local data? The plugin already loads its state from localstorage, so no need to check it yourself.

**Comment by robinvdvleuten** [comment]
For Vuex or this plugin there is no difference between local or remote data. Just fetch something from your actions and persist that into your store.
