### ISSUE TITLE
vuex-persistedstate not working on local env

### ISSUE THREAD

**Issue by alexandruflorea** [robinvdvleuten/vuex-persistedstate#188]
I'm trying to report an error, as I think.

### Steps to reproduce

Installed Vuex@3.1.0 and Vuex-persistedstate@2.5.4 in a project using npm.

Configured the project's store like this:

`import Vue from 'vue'
import Vuex from 'vuex'
import createPersistedState from 'vuex-persistedstate'

Vue.use(Vuex)

const state = {
    count: 0
}

export default new Vuex.Store({
    state,
    plugins: [createPersistedState()]
})`

Integrated in a parent file like this:

`import Vue from 'vue'
import store from './store/store'
import App from './App.vue'

Vue.config.productionTip = false
new Vue({
    el: '#root',
    template: '<app></app>',
    store,
    components: {
        App
    },
    router
})`

And after this running `npm run watch` the application does not persist the state in localStorage.
Tested in Google Chrome, Firefox, Safari, all latest versions in both incognito and normal navigation mode.

### Expected behavior

The vuex.count to be persisted in localStorage.

**Comment by beebase** [comment]
Are you updating vuex state directly through actions?

```
actions : {
  doSomething(ctx, payload) {
    ctx.state.someField = payload
```

I noticed that vuex-persistedstate wasn't updating, so I changed my action, and let
mutations handle the state change (the proper way).

```
actions : {
  doSomething(ctx, payload) {
   ctx.commit('SET_FIELD', payload)
  }
},
mutations : {
 SETFIELD(state, payload) {.....
```

I think in general, vuex plugins are only triggered by mutations.
[vuex docs (plugins)](https://vuex.vuejs.org/api/#plugins)
Not sure if this is also the case with vuex-persistedstate.
