### ISSUE TITLE
How to use with Quasar Framework

### ISSUE THREAD

**Issue by folamy** [robinvdvleuten/vuex-persistedstate#189]
`import Vue from 'vue'
import Vuex from 'vuex'

import createPersistedState from 'vuex-persistedstate'
import cartModule from './cartModule'
import customer from './customer'
import contents from './contents'

Vue.use(Vuex)
export default function ({ ssrContext }) {
  const Store = new Vuex.Store({
    modules: {
      cartModule,
      customer,
      contents
    }
    plugins: [createPersistedState({
      paths: ['cartModule/cart', 'cart']
    })]
  })
  return Store
}`
this doesnt work with quasar

**Comment by robinvdvleuten** [comment]
This has nothing to do with Quasar. Can you provide at least a runnable codesandbox? I cannot recreate everybody's setup and use cases.

**Comment by folamy** [comment]
I tried codesandbox, it run perfectly but my real app is in ssr mode 
Could that be the problem ?

**Comment by folamy** [comment]
found the problem! I was running the app on SSR mode but, When I disable SSR run SPA mode it works.
But I need for SSR mode because my app is suppose to be run on SSR mode.....

**Comment by robinvdvleuten** [comment]
I don't use the Quasar framework myself, so you'll have to provide something more than just saying "it doesn't work". But in a glance, it looks like an issue with your project's setup and not with this plugin.

**Comment by ertgl** [comment]
@folamy You can try using cookies by parsing SSR context.

```
import Vue from 'vue'
import Vuex from 'vuex'

import { Cookies } from 'quasar'
import createPersistedState from 'vuex-persistedstate'

Vue.use(Vuex)

export default function ({ ssrContext }) {
  const cookies = process.env.SERVER ? Cookies.parseSSR(ssrContext) : Cookies
  const Store = new Vuex.Store({
    plugins: [
      createPersistedState({
        storage: {
          getItem: key => {
            return cookies.get(key)
          },
          setItem: (key, value) => {
            return cookies.set(key, value, {
              path: '/',
              expires: 365
            })
          },
          removeItem: key => {
            return cookies.remove(key)
          }
        },
        getState: (key, storage, value) => {
          value = storage.getItem(key)
          return value
        },
        setState: (key, state, storage) => {
          return storage.setItem(key, state)
        }
      })
    ]
  })

  return Store
}
```

I hope this helps.

**Comment by sebastianjung** [comment]
so it was working for me on ssr mode by simply adding this as a bootfile:

```
import createPersistedState from "vuex-persistedstate";

export default function({ store }) {
  createPersistedState({
    paths: ["settings"]
  })(store);
}
```

in quasar.conf.js:
```
boot: [
      {
        server: false,
        path: "vuex-persistedstate"
      },
      ...
]
```
