### ISSUE TITLE
if the actions type are promise?

### ISSUE THREAD

**Issue by zhougonglai** [robinvdvleuten/vuex-persistedstate#19]
After I add the plugin are wrong:
`Uncaught (in promise) TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at setState (eval at <anonymous>`
on the line : vuex-persistedstate.js?2e1f:80

The following is my actions：
![myactions](https://cloud.githubusercontent.com/assets/10954751/25120579/5445ed4c-2451-11e7-8f8e-9c31a9420b2f.png)

**Comment by robinvdvleuten** [comment]
Looks like a bug in your implementation. You'll need to check if you're passing in valid json into the store.
