### ISSUE TITLE
could you make the plugin to support 'indexDB' or you can use the libary of 'localforage'  to cache vuex state

### ISSUE THREAD

**Issue by yisibell** [robinvdvleuten/vuex-persistedstate#190]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by robinvdvleuten** [comment]
@yisibell please see https://github.com/robinvdvleuten/vuex-persistedstate#%EF%B8%8F-localforage-%EF%B8%8F. But PRs for adding this functionality are always welcome.
