### ISSUE TITLE
State not in sync between different apps

### ISSUE THREAD

**Issue by gubarez** [robinvdvleuten/vuex-persistedstate#192]
Original Vuex syncs state between different apps using the same store instance. The plugin seems to break this feature. Doesn't anyone have any suggestions how state sync could be achieved?

**Comment by robinvdvleuten** [comment]
> If you try to report a bug but do not not provide a reproducible codesandbox or fiddle, the issue will be closed without further notice.

Please move all questions to StackOverflow please.
