### ISSUE TITLE
Getting values inside mounted() / created()

### ISSUE THREAD

**Issue by l2aelba** [robinvdvleuten/vuex-persistedstate#193]
I have a question about **getting values** after init like ```mounted()``` or ```created()```

This is how it setup values
```js
export const state = () => ({
  storage: {
    myValue: null
  }
})
```

```js
computed: {
  ...mapState([
    'storage'
  ])
}
```

Problem is when I want to get values after init like
Example: When localStorage set to some to value like ```myValue: 'clicked'```
```js
mounted () {
  const self = this
  console.log( self.storage.myValue ) // --> null  (default value!  not work! too fast!)
  setTimeout(() => {
    console.log( self.storage.myValue ) // --> 'clicked' (it's work!, but this is safe?)
  })
  window.onNuxtReady(() => {
    console.log( self.storage.myValue ) // --> 'clicked' (it's work!, but just one time after Nuxt ready)
  })
}
```

**Question is** anyway better way and 100% to making sure value should be able to get it?

I think about using ```setTimeout``` and ```onNuxtReady```  is not a good idea. ???

**Comment by z3to** [comment]
I think this is similar to #150.

I have been using this in the `localStorage.js` plugin for now:
```js
import createPersistedState from 'vuex-persistedstate'

export default ({ store }) => {
  window.onNuxtReady(() => {
    const { dispatch } = store
    createPersistedState({
      paths: ['myValue']
    })(store)
    dispatch('initApp')
  })
}
```

The `initApp` action then triggers everything to start.

**Comment by robinvdvleuten** [comment]
@z3to thanks for answering the question. I am not a Nuxt user myself so it's quite hard to figure out all those situations where people run in to.
.
