### ISSUE TITLE
vue-persist doesn't support NUXT universal mode

### ISSUE THREAD

**Issue by simon-zhangmuye** [robinvdvleuten/vuex-persistedstate#194]
Hi there, I am tring to use vuex-persistedstate in my nuxt project. But it doesn't work. I am working with universal mode. Here is my config. Can you tell me how can i fix this problem. Thank you very much.
Here is my code
```
// plugins/vuex-persistedstate.js
import createPersistedState from 'vuex-persistedstate'
export default ({store}) => {
  // your option
  createPersistedState({
    key: 'vuex',
    paths: []
  })(store)
}
```
```
//nuxt.config.js
  plugins: [
    { src: '@/plugins/vuex-persistedstate.js', ssr: false },
  ],
```

**Comment by robinvdvleuten** [comment]
I don't known, never used Nuxt. Please raise an issue at their repository or go to StackOverflow. Thank you very much.

**Comment by simon-zhangmuye** [comment]
I just fix the problem. This is because of browser cache and it works now. Thank you for your reply.

**Comment by scriptcoded** [comment]
@simon-zhangmuye how did you solve your problem? I'm having odd issues with Nuxt, and am hoping we might have run in to the same issue.

**Comment by alterhu2020** [comment]
I had met the error when working with nuxt ,the error as below:

```
TypeError: Cannot read property 'subscribe' of undefined
    at vuex-persistedstate.es.js:1
    at push../node_modules/vuex-persistedstate/dist/vuex-persistedstate.es.js.__webpack_exports__.default (vuex-persistedstate.es.js:1)
    at vuex-persist.js:8
    at client.js:549
    at Array.forEach (<anonymous>)
    at nuxtReady (client.js:547)
    at client.js:698
    at Array.<anonymous> (vue.runtime.esm.js:1980)
    at flushCallbacks (vue.runtime.esm.js:1906)

```
