### ISSUE TITLE
Kinda new How do we know if cookie expire

### ISSUE THREAD

**Issue by donPuerto** [robinvdvleuten/vuex-persistedstate#196]
I was wondering, what happen if the cookie expire?

At my test? both of them persist.
![image](https://user-images.githubusercontent.com/9329005/56145841-a4dc0200-5fd7-11e9-9682-d53582f26a47.png)

1day
![image](https://user-images.githubusercontent.com/9329005/56145870-bb825900-5fd7-11e9-90e0-c4dff3dbc08f.png)

1min
![image](https://user-images.githubusercontent.com/9329005/56145891-cdfc9280-5fd7-11e9-9bf4-a58eebbde42a.png)

Just to test their expiration date

**Comment by robinvdvleuten** [comment]
The cookie won't be there if it is expired, that's your test. Just check for a null or undefined cookie with the `js-cookie` library.
