### ISSUE TITLE
Cannot access persisted vuex store data in middleware.

### ISSUE THREAD

**Issue by simon-zhangmuye** [robinvdvleuten/vuex-persistedstate#197]
My vuex state has been stored in localstorage, but I cannot access vuex stored data in middleware.
I guess the problem may because, when I refresh the page, middleware is loaded before vue persist sets values to vuex.
Is there any way to solve this problem?
![20190417230451](https://user-images.githubusercontent.com/10706610/56299263-42fdd280-6166-11e9-8604-652d69d30f48.png)

**Comment by ZenekeZene** [comment]
Did you have the solution?

**Comment by Mucaccino** [comment]
How about?
