### ISSUE TITLE
How can I store data in both localStorage and SessionStorage at the same time.

### ISSUE THREAD

**Issue by simon-zhangmuye** [robinvdvleuten/vuex-persistedstate#198]
Same as the topic.

**Comment by robinvdvleuten** [comment]
Just initialize the plugin twice with different configurations. Move questions to StackOverflow please and use Github issues for reporting actual issues.

**Comment by eddivalen** [comment]
Hey @robinvdvleuten, I want to save some data on the localStorage, and other on the sessionStorage, How I can achieve that?

**Comment by robinvdvleuten** [comment]
@eddivalen just initialize the plugin twice with different configurations;

```js
import createPersistedState from "vuex-persistedstate";

const store = new Vuex.Store({
  // ...
  plugins: [
    createPersistedState({ /* config for localStorage */ }),
    createPersistedState({ /* config for sessionStorage */ })
  ],
});
```

**Comment by eddivalen** [comment]
Hey @robinvdvleuten , I tried this but it seems the 2nd config is overriding the 1st one, I'm also using a module, here's my config:

```
plugins: [createPersistedState({
    paths: 'template.state',
    storage: window.localStorage
  })],
  plugins: [createPersistedState({
    storage: window.sessionStorage
  })],
```

So my idea is to save the template module in the localStorage, and the other one in the sessionStorage

**Comment by eddivalen** [comment]
Sorry @robinvdvleuten , my issue was on the paths, I was passing a string and it expects an array.

Thank you for your help.
