### ISSUE TITLE
State cant't change

### ISSUE THREAD

**Issue by Mr-wang007s** [robinvdvleuten/vuex-persistedstate#199]
* State cannot be changed after a page refresh using vuex-persistedstate 

```
//"vuex-persistedstate": "^2.5.4"
export default new Vuex.Store({
	state,
        modules,
	actions,
	mutations,
    plugins: [createPersistedState()]
})

```

**Comment by TonhaoSantos** [comment]
I'm with this same problem

**Comment by gongph** [comment]
@raphaelsaunier  Hi, The data of saved vuex-persistedstate havn't refresh
- Version: `"vuex-persistedstate": "^2.5.4"`

**Comment by robinvdvleuten** [comment]
Please move the question to the Vue Forum or StackOverflow.
