### ISSUE TITLE
store.subscribe not being triggered 

### ISSUE THREAD

**Issue by LeonLiber** [robinvdvleuten/vuex-persistedstate#20]
Hi,

I'm using vuex-persistedstate and I need to subscribe to the "value resetting event".

I added `store.subscribe` to my store but it is not being triggered when the values are put back after refresh.

Amu I missing something?

Thanks

**Comment by robinvdvleuten** [comment]
@LeonLiber can you please provide a https://jsfiddle.net/ with your situation / example of your setup?

**Comment by LeonLiber** [comment]
Hi @robinvdvleuten, It's a bit of a complicated setup for jsfiddle so I'll try to post it here.

The core of the store looks like that:

```javascript
import Vue from 'vue';
import Vuex from 'vuex';
import persistedState from 'vuex-persistedstate';

Vue.use(Vuex);

export default new Vuex.Store({
  plugins: [persistedState({
    paths: ['user'],
  })],
  state: {
    user: { },
  },
  getters: {
    isUserLoggedin(state) {
      return Object.keys(state.user).length > 0;
    },
    user(state) {
      return state.user;
    },
  },
  mutations: {
    SET_USER(state, userData) {
      state.user = userData;
    },
    UNSET_USER(state) {
      state.user = {};
    },
  },
  actions: {
    setUser({ commit }, userData) {
      commit('SET_USER', userData);
    },
    unsetUser({ commit }) {
      commit('UNSET_USER');
    },
  },
});
```

I want to subscribe to any change "resetting" of the user so I can set some default http headers with the proper user token.

This is what I tried:

```javascript
 store.subscribe((mutation) => {
   console.log('MUTATED', mutation);
});
```

And I get no log when `user` is re-set after page refresh.

Thanks you

**Comment by robinvdvleuten** [comment]
@LeonLiber so as I try to understand your issue, you are trying to set custom axios headers when your app is initialised right?

**Comment by LeonLiber** [comment]
Correct. The token I'm going to store in the header is coming from the persistent store so I need to act on the state "rehydration"

**Comment by robinvdvleuten** [comment]
@LeonLiber why not fetch the correct header from the store when initializing your app (so after the store is dehydrated). Please see both urls for an example;

https://github.com/robinvdvleuten/vue-auth0-vuex/blob/master/template/src/router/index.js#L36
https://github.com/robinvdvleuten/vue-auth0-vuex/blob/master/template/src/router/index.js#L9

This `onEnter` hook dispatches an event which will fetch a new token. You can use the same pattern for setting the header on axios by fetching the value from the store.
