### ISSUE TITLE
Vue.delete property reappears after refresh

### ISSUE THREAD

**Issue by bartvanremortele** [robinvdvleuten/vuex-persistedstate#200]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Using `Vue.delete` the property removed from the state object get's put back on refresh.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://codesandbox.io/embed/m37z15yvxp
Press remove property button then reload. You'll see that the property is back.

**What is the expected behavior?**
Using `Vue.delete` also persists the delete in localstorage. Property is still deleted on refresh.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by Cightline** [comment]
+1

**Comment by intermundos** [comment]
+1

**Comment by robinvdvleuten** [comment]
I don't see why you need `Vue.delete` for this as the reactivity is already handled by Vuex. Please use Vanilla Javascript for such cases;

```js
const store = new Vuex.Store({
  state: {
    count: 0,
    1: 'Property',
    2: 'Property'
  },
  plugins: [createPersistedState()],
  mutations: {
    increment: state => state.count++,
    decrement: state => state.count--,
    removeProperty: state => ({ count: state.count, 2: state[2] }),
  }
});
```
