### ISSUE TITLE
shvl Undefined in latest version

### ISSUE THREAD

**Issue by CrashyBang** [robinvdvleuten/vuex-persistedstate#201]
**Do you want to request a *feature* or report a *bug*?**

Bug Report.

**What is the current behavior?**

Getting the following error on this like `const savedState = shvl.get(options, 'getState', getState)(key, storage);`:

```
Uncaught (in promise) TypeError: Cannot read property 'get' of undefined
    at index.js:56
    at vuex.js:358
    at Array.forEach (<anonymous>)
    at new Store (vuex.js:358)
    at script.js:157
    at s (runtime.js:45)
    at Generator._invoke (runtime.js:271)
    at Generator.t.<computed> [as next] (runtime.js:97)
    at i (asyncToGenerator.js:5)
    at u (asyncToGenerator.js:27)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Load in vuex and vuex-persisted state:
```
<script src="https://cdn.jsdelivr.net/npm/vuex@3.1.1/dist/vuex.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vuex-persistedstate@2.5.4/dist/vuex-persistedstate.umd.js"></script>
```
Initialize:
```js
 window.store = new Vuex.Store({
    state: {},
    mutations: {},
    actions: {},
    plugins: [createPersistedState()]
});
```

Open browser and see the afore mentioned error.

[EXAMPLE (JSFiddle)](https://jsfiddle.net/8ayqhtLj/);

**What is the expected behavior?**

No error.

**If this is a feature request, what is motivation or use case for changing the behavior?**

N/A

**Comment by robinvdvleuten** [comment]
Seems that you are missing the plugin's dependencies;

https://cdn.jsdelivr.net/npm/shvl@2.0.0/dist/shvl.umd.js
https://cdn.jsdelivr.net/npm/deepmerge@3.2.0

**Comment by CrashyBang** [comment]
Hey @robinvdvleuten,

Awesome that looks like it has fixed it, I assume that is happening because I am using the `umd` version of the library?

Cheers!

**Comment by robinvdvleuten** [comment]
This has nothing to do with the build, all dependencies are just not included in the output.
