### ISSUE TITLE
Blocked cookies breaks app

### ISSUE THREAD

**Issue by cliffordh** [robinvdvleuten/vuex-persistedstate#202]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
If cookies are enabled then program works. If cookies are disabled (Safari Mac) then site breaks.

**If the current behavior is a bug, please provide the steps to reproduce.**
Using latest Safari on Mac OS X Mojave disable  ALL cookies. When loading app a SecurityError is thrown inside VueX. 

**What is the expected behavior?**
If cookies are disabled then I would expect the program to silently fail to persist.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by robinvdvleuten** [comment]
"If cookies are disabled then I would expect the program to silently fail to persist." gives me issues from other users of the plugin who don't understand why nothing is persisting. Throwing an error makes it explicit what goes wrong within your app and I suggest handling this yourself in the `storage` option;

```js
export default ({store}) => {
  window.onNuxtReady(() => {
    createPersistedState({
      storage: {
        getItem: key => Cookies.get(key),
        setItem: (key, value) => {
          try {
            Cookies.set(key, value, { expires: 3, secure: true })
          } catch (err) {
		    // Handle the exception here yourself 👋
          }
        },
        removeItem: key => Cookies.remove(key),
      },
    })(store)
  })
}
```
