### ISSUE TITLE
Should it be possible or not to use vuex-persistedstate in universal mode

### ISSUE THREAD

**Issue by LOUKOUKOU** [robinvdvleuten/vuex-persistedstate#205]
First of all I did get it to work in universal mode, but I don't think it intended to work. It seems like it loads the js server-side first then changes it later to the local storage to a disasters effect.

So my main question? Is it meant to work in universal mode?
My second question? Why does the below code work when im not configuring it properly? But when I do configure it properly it gives me the ``window not found error`` error.

Would it just be best to do spa mode?

Here is my code:

nuxt.config.js
```
mode: 'universal',
plugins: [{ src: '@/plugins/localStorage.js', ssr: false }] ,
```

plugins/localStorage.js
```
import createPersistedState from 'vuex-persistedstate'

export default ({ store }) => {
  // your option
  createPersistedState({
    key: 'vuex',
    paths: ['windows']
  })(store)
}
```

store/windows.js
```
// import VuexPersist from 'vuex-persistedstate'

// export const plugins = [VuexPersist({ storage: window.sessionStorage })]

export const state = {
  navCollapsed: true
}

export const mutations = {
  setNavCollapsed(state, isCollapsed) {
    state.navCollapsed = isCollapsed
  }
}
```

**Comment by LOUKOUKOU** [comment]
Okay so it works a bit better if i change:

plugins/localStorage.js

```
import createPersistedState from 'vuex-persistedstate'

export default ({ store }) => {
  // your option
  createPersistedState({
    key: 'vuex',
    paths: ['windows']
  })(store)
}
```

to

```
import createPersistedState from 'vuex-persistedstate'

export default ({ store }) => {
  // your option
  window.onNuxtReady(() => {
    createPersistedState({
      key: 'vuex',
      paths: ['windows']
    })(store)
  })
}
```

**Comment by goors** [comment]
this will only work on client-side. you told ssr: false; disble javascript in browser ot see what will happen.
