### ISSUE TITLE
QuotaExceededError on iOS Chrome

### ISSUE THREAD

**Issue by jafri** [robinvdvleuten/vuex-persistedstate#206]
This is a bug, seeing a QuotaExceededError on iOS Chrome (not incognito). Error was seen after stored config was updated. Likely a similar error to https://github.com/marcuswestin/store.js/issues/232

**Comment by robinvdvleuten** [comment]
This is not a bug, just expected browser behaviour. You probably are storing too much into the localstorage instance through this plugin. Please revisit your application logic.

**Comment by jafri** [comment]
It is only storing 5 key value pairs, this bug should not be occurring outside of incognito mode.

**Comment by gabrielsclimaco** [comment]
It is also happening to me storing an array with 10 items, this definitely isn't normal.

**Comment by jafri** [comment]
@robinvdvleuten this is not a closed issue

**Comment by robinvdvleuten** [comment]
@jafri it is. Otherwise please post a reproducible case or a PR with a fix for the issue. I do not have the time to investigate everybody's setup.

**Comment by PabloRN** [comment]
> @robinvdvleuten this is not a closed issue

Did you find a solution to this?
