### ISSUE TITLE
Performance improvement by splitting keys?

### ISSUE THREAD

**Issue by edwh** [robinvdvleuten/vuex-persistedstate#209]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Performance degrades as the store size increases.

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a largish store (a couple of MB).  Browser hangs noticeably when state is persisted.

**What is the expected behavior?**

Performance doesn't degrade.

**If this is a feature request, what is motivation or use case for changing the behavior?**

In my experience, local storage performance degrades as the value size increases.  Since the entire store is serialised into a single string, for large stores the performance degrades to the point where there are noticeable browser delays.

Is there a way to make this plugin split the data across multiple local storage keys to improve performance?  Has anyone considered this?

**Comment by robinvdvleuten** [comment]
Yeah this plugin is never meant to store large stores. Please restructure your application so it doesn't store multiple MBs in local storage.

**Comment by Nikey646** [comment]
Maybe have per-module storage, so each module is able to store it's state in a dedicated LS Key.

Also possibly providing compression to reduce the storage size further on large states would result in performance improvements? This would definitely help for alternative storage mediums, such as cookies.
