### ISSUE TITLE
Plugin Does not store Moment(moment.js) object as object in local storage, rather it is stored as string

### ISSUE THREAD

**Issue by preetishhs** [robinvdvleuten/vuex-persistedstate#213]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
State variable has moment(moment.js) object
```
state: {
  num: moment(Date())
}
```
`num` actually holds a moment object, when I see local storage, I see a string instead.
So when I refresh my page, Vuex is cleared and it fetches from local storage after that any operations done on `num` such as num.week() etc will return in error.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is the codesandbox link
https://codesandbox.io/s/vuex-persistedstate-f2885

1. Run the sandbox, It works fine the first time(no errors in the console, you can see today's date)
2. Just increment/decrement the count and check local storage
3. As you can see the local storage, `num` is stored as a string instead of Moment Object.

4. Then refresh the codesandbox internal browser, in the internal console we can see this error `TypeError: store.state.num.format is not a function`

**What is the expected behavior?**
Moment object should not be stored as a string, rather it should be stored as Object itself.

**Comment by robinvdvleuten** [comment]
Yeah you have to serialize and deserialize the moment instance yourself. The plugin is not going to do that. Please move the question to the Vue Forum or StackOverflow.
