### ISSUE TITLE
Data dont persist with multiple storage

### ISSUE THREAD

**Issue by 50l3r** [robinvdvleuten/vuex-persistedstate#215]
Hi guys,

I have 3 persistedstate plugins with different storage types and timings:

    import Vue from 'vue';
    import Vuex from 'vuex';
    import createPersistedState from 'vuex-persistedstate';

    import * as Cookies from 'js-cookie';

    Vue.use(Vuex);

    const plugins = [
        createPersistedState({
            key: 'Gestios',
            paths: [
                'Gestios',
            ],
        }),
        createPersistedState({
            key: 'GestiosCache',
            paths: [
                'GestiosCache',
            ],
            storage: {
                getItem: (key) => {
                    JSON.parse(Cookies.get(key));
                },
                setItem: (key, value) => {
                    value = JSON.parse(value)[key];
                    Cookies.set(key, value, { expires: 3, secure: false });
                },
                removeItem: key => Cookies.remove(key),
            },
        }),
        createPersistedState({
            key: 'Settings',
            paths: [
                'Settings',
            ],
            storage: {
                getItem: (key) => {
                    console.log(JSON.parse(Cookies.get(key)));
                    JSON.parse(Cookies.get(key));
                },
                setItem: (key, value) => {
                    value = JSON.parse(value)[key];
                    Cookies.set(key, value, { expires: 12, secure: false });
                },
                removeItem: key => Cookies.remove(key),
            },
        }),
    ];

    // LOAD MODULES
    const modules = {};
    const files = require.context('../store/', false, /\.js$/);
    files.keys().forEach((key) => {
        modules[key.replace(/(\.\/|\.js)/g, '')] = files(key).default;
    });

    export default new Vuex.Store({
        modules,
        plugins,
        strict: process.env.NODE_ENV !== 'production',
    });

Gestios key store data in localstorage. GestiosCache and Settings in Cookies.

![](https://i.gyazo.com/d78032f5f8baed38baa8ab67d9968145.png)

I have a problem. I update my cookie but when i reload the page data have been reset.

Any ideas?

**Comment by miladganjali** [comment]
I have same problem @50l3r do you find a solution? on refresh, the data is gone!

**Comment by 50l3r** [comment]
> I have same problem @50l3r do you find a solution? on refresh, the data is gone and only happens when I use Cookie!

There's a problem with cookie secure option:

    storage: {
        getItem: key => Cookies.getJSON(key),
        setItem: (key, value) => {
            value = JSON.parse(value)[key];
            Cookies.set(key, value, { expires: 3, secure: false });
        },
        removeItem: key => Cookies.remove(key),
    },

If you set to false it works
