### ISSUE TITLE
writing all modules inside paths doesn't update Cookies

### ISSUE THREAD

**Issue by serj99** [robinvdvleuten/vuex-persistedstate#216]
This is where I create Store:
```
const store = new Vuex.Store({
  state: {
  },
  mutations: {
  },
  getters: {
  },
  modules: {
   module4,
   module3,
   module2,
   module1,
  },
  plugins: [createPersistedState({
    paths: ['module1', 'module2', 'module3', 'module4'],
    storage: {
      getItem: key => Cookies.get(key),
      setItem: (key, value) => Cookies.set(key, value, { expires: 3, secure: true }),
      removeItem: key => Cookies.remove(key)
    }
  })],
})
```

Default values are written but not updated until I do logout. Another array with same behaviour:
- [ 'module2', 'module3', 'module4']

It updates as it should If inside plugin I change paths array to:
-  [''module4']
-  [ 'module3', 'module4']
-  [ 'module2', 'module4']
-  [ 'module1', 'module4']
-  [ 'module2', 'module1', 'module4']

What should I watch for?

**Comment by macarthuror** [comment]
Do you have any error in console?

I don't know how many data you are trying to store in the cookie but you need to have in mind that the cookies only supports **4096 bytes**.

If you want it you can check it an example of how I use `vuex-persistedstate` with `js-cookie` and **Modules**. Hope that can help you 🤞😁

[![Edit vuex-persistedstate with js-cookie using Vuex Modules](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vuex-persistedstate-f9hxw?fontsize=14)

**Comment by serj99** [comment]
Inside one of the modules there was an array state which during application interaction at a later time was loaded with lots of objects. I measured size and were more than 20 000 bytes. I solved by moving this module to the local storage.
