### ISSUE TITLE
Switch key at runtime

### ISSUE THREAD

**Issue by sebastian-raubach** [robinvdvleuten/vuex-persistedstate#218]
**Do you want to request a *feature* or report a *bug*?**
More of a question, but feature will do.

**What is the current behavior?**
I currently use the `key` property of vuex-persistedstate to differentiate between different deployments of my website (say A and B). A will use key 'a' and B will use key 'b'. That all works fine.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Now I'm in the situation where the things stored in the store are user-specific. Even when I'm only using A, there will be multiple users. I would like to know if it's possible to change the key on the fly. Say from 'A-userId1' to 'A-userId2'.
There's no secret data in the store, it's just for convenience that if a user logs in on the machine and logs in as a different user, they stored properties don't get mixed up.

Now, I know I know I can make this work by having an object with the userId as the key and then all properties of that user underneath, but it would be neater if it could be done by switching keys.

Is this possible?

**Comment by sebastian-raubach** [comment]
Any update on this? I would really like to be able to switch keys at runtime so that I don't mix up users' preferences.
If there's another way to do it, that'd be fine as well.

**Comment by sebastian-raubach** [comment]
Ok, I ended up adding the generic parameters to the root of the state and then having a `userStates` object that contains the specific settings with the user's id as the key.
Just had to remember to add a new user by using `Vue.set(...)` to make it reactive. The getters then return the value based on the currently logged in user.
If there is no interest in supporting changing keys at runtime, then I guess this issue can be closed as I found a solution that works for me.

**Comment by johnclendvoy** [comment]
Sebastian, is there any chance you could share part of your vuex store file where you are creating/setting the keys? I am working on something very similar and need to create unique keys based on a few parameters. It sounds like the solution you came up with might work for me as well but I am having a hard time visualizing it. Thanks!

**Comment by sebastian-raubach** [comment]
> Sebastian, is there any chance you could share part of your vuex store file where you are creating/setting the keys? I am working on something very similar and need to create unique keys based on a few parameters. It sounds like the solution you came up with might work for me as well but I am having a hard time visualizing it. Thanks!

The code I use is available here: https://github.com/sebastian-raubach/germinate-vue/blob/master/src/store/store.js

The `getters` use the `userId` to get the correct item from the `userStates` object.
When a new one is added, the `ON_TOKEN_CHANGED_MUTATION` sets the default user state for this new user id. The custom methods of the persisted state (`getItem` etc) will likely not be necessary in your case, they're just for GDPR compliance.

Hope this helps.

**Comment by robinvdvleuten** [comment]
If this is still relevant, please open a new issue.
