### ISSUE TITLE
Firefox 70 - Update Error: Invalid storage instance given

### ISSUE THREAD

**Issue by db-add2** [robinvdvleuten/vuex-persistedstate#222]
After updating to FF 70 my app is broken and I get:

**Error: Invalid storage instance given 
vuex-persistedstate.es.js:1**

In inkognito mode the app is working as expected.

I've clear whole cookies, cache and storage, but still getting that error.

Please advise.

**Comment by robinvdvleuten** [comment]
The plugin now throws the actual error you'll getting. Hopefully that helps.
