### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by DanielRuf** [robinvdvleuten/vuex-persistedstate#224]
There are some changes in the readme and type definition files. Might be a good idea to publish a new release to get this to npmjs.com:

https://github.com/robinvdvleuten/vuex-persistedstate/compare/v2.5.4...master

**Comment by robinvdvleuten** [comment]
You're absolutely right! https://github.com/robinvdvleuten/vuex-persistedstate/releases/tag/v2.6.0
