### ISSUE TITLE
persist the store between server and the client

### ISSUE THREAD

**Issue by wiadev** [robinvdvleuten/vuex-persistedstate#226]
Hi
Is there a way to persist the store between the server and the client?

I have a nuxtjs project and I need to fetch the data in page-fetch.
```
async fetch ({ store }) {}
```

I've kept the store in the local storage and it's not accessible on the server.

Is there a way to sync between server and client?

Many thanks.

**Comment by robinvdvleuten** [comment]
This is out of scope of this plugin. Please move to StackOverflow or Vuejs Forum for such questions.
