### ISSUE TITLE
能同时存储sessionstorage和localstorage么

### ISSUE THREAD

**Issue by kaizi311** [robinvdvleuten/vuex-persistedstate#229]
- `vuex-persistedstate` version:
- `node` version:
- `npm` (or `yarn`) version:

Relevant code or config

```javascript
```

What you did:

What happened:

Reproduction sandbox:

Problem description:

Suggested solution:

**Comment by robinvdvleuten** [comment]
Yeah I don't speak Chinese. I'm sorry.
