### ISSUE TITLE
Remove any dependency from the project

### ISSUE THREAD

**Issue by robinvdvleuten** [robinvdvleuten/vuex-persistedstate#23]
Both the __lodash.merge__ and __object-path__ package should be removed as dependency.

**Comment by ElForastero** [comment]
Yep. Definitely.

**Comment by piehei** [comment]
Any update on this one? :)

Thank you for the great plugin anyhow!!!

**Comment by robinvdvleuten** [comment]
The `object-path` is already removed as dep. Still looking for a lean deep merge alternative.
