### ISSUE TITLE
Add support of versioning persisted store

### ISSUE THREAD

**Issue by Koc** [robinvdvleuten/vuex-persistedstate#231]
Sometimes during updates we need change structure of internal storage (due to refactoring or switching to another backend implementation). For now there is no possibility to do it automatically.

Would be nice add support of vuex modules versioning and add possibility to execute some migration between version changes. Or at least clear persisted storage.

**Comment by juanvillegas** [comment]
I do that as follows:

```
window.localStorage.removeItem('storev3');
createPersistedState({
    key: 'storev4',
    // other options
})
```

That is, clear the old key and set a new one for the State.

**Comment by robinvdvleuten** [comment]
If this is still relevant, please open a new issue.

**Comment by vtonchev** [comment]
Would be great if there was such a function

**Comment by giddens9527** [comment]
Yes, and as I know, redux-persist has this kind of feature (versioning + migration).
