### ISSUE TITLE
Add support of listening local storage changes (cross-tab communication)

### ISSUE THREAD

**Issue by Koc** [robinvdvleuten/vuex-persistedstate#232]
This issue relates to #180.

What you did:
1. open [example](https://codesandbox.io/s/80k4m2598) from doc in 2 tabs
2. increment counter 4 times in 1st tab
3. increment counter 1 time in 2nd tab
4. refresh both tabs

What happened:
Increment from 2nd tab overrides actual state from 1st tab.

Reproduction sandbox:
https://codesandbox.io/s/80k4m2598

Suggested solution:
Would be nice add support of listening local storage changes for merging state changes between tabs. For reducing time needed for merge and prevent race conditions consider store each vuex module in separate local storage key (now all store with modules stored in `vuex` key).

**Comment by robinvdvleuten** [comment]
This is out of the scope for this plugin. Please pass a custom storage as option and use event listeners to sync the tabs yourself.

**Comment by Koc** [comment]
This is sad. Because users that work in multiple tabs will loose their actual state all the time.

Even more, it is hard to realize through own storage because all modules stored in the same key. Is it possible to provide any option to plugin to store each module in the separate local storage key?

**Comment by BevanR** [comment]
```ts
// Reload state from disk when it changes in any other tab.
// @see https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event
window.addEventListener('storage', event => {
  if (event.key === 'vuex') {
    store.replaceState(JSON.parse(localStorage.vuex))
  }
})

```

Related;

- https://github.com/robinvdvleuten/vuex-persistedstate/issues/232
- https://github.com/robinvdvleuten/vuex-persistedstate/issues/234
- https://github.com/robinvdvleuten/vuex-persistedstate/issues/180
