### ISSUE TITLE
Persist only part of path (but keep all of it in memory)

### ISSUE THREAD

**Issue by jarvelov** [robinvdvleuten/vuex-persistedstate#24]
Is there any way to partially persist a path in the vuex state in localStorage and still keep the rest in the vuex state but only memory?

So I expected to be able to tackle this problem with a reducer function to only persist what I wanted.

In the code below the reducer function aims to persist any `texts` written by the currently logged in user (`state.User.user.id`) so they can be accessible even if the client is offline. However, this effectively filtered  any `texts` NOT written by the current user out of vuex altogether.

Is there any way for localStorage to coexist with the in-memory store that vuex uses out of the box?

```js
import _ from 'lodash'

const reducer = (state, paths) => (
  paths.length === 0 ? state : paths.reduce((substate, path) => {
    const value = _.get(state, path)

    switch (path) {
      case 'texts':
        // Only persist texts which are submitted by the current user
        value.items = value.items.filter(item =>
          (item.user && item.user.id === state.User.user.id))
        break
    }

    _.set(substate, path, value)

    return substate
  }, {})
)

export default reducer
```

**Comment by robinvdvleuten** [comment]
Please take a look at the "paths" option; _An array of any paths to partially persist the state. If no paths are given, the complete state is persisted. (default: [])_. If you pass an array of string paths, these paths will be persisted and the rest will be kept in memory. 

To extend this functionality you can add a custom reducer method like you did where you can return a custom persisted state object. I can't immediately tell what goes wrong in your example, so I guess you'll need to debug there.

**Comment by jarvelov** [comment]
Just wanted to leave some feedback in case anyone else comes across this.

What I accidentally did was that `const value = _.get(state, path)` actually returns the reference to the property in vuex's state. Thus the filter mutated the original state.

Thanks for this great plugin.
