### ISSUE TITLE
Release of 2.7 break backward compatibility

### ISSUE THREAD

**Issue by utlime** [robinvdvleuten/vuex-persistedstate#241]
- `vuex-persistedstate` version: 2.7.0
- `node` version:10
- `npm` (or `yarn`) version:6

```javascript
import createPersistedState from 'vuex-persistedstate'

localStore.setItem('key', 'old value'); // put value before creating

const persistatedStore = createPersistedState(someOptions)

const store = new Vuex.Store({ ... })

localStore.setItem('key', 'new value'); // update value in storage before using

persistatedStore(store)

assert(store.state.key === 'new value', 'store keep old value')
```

**Problem description:**
2.7.0 release breaks backward compatibility with 2.6 version. After update to 2.7 our unit tests start to be failed, because it doesn't load fresh state when you actually **use** plugin.
I found that it releated to #225 
Will explain with help of example from PR.

**Suggested solution:**
Could you please rollback related changes from PR and release patch 2.7.1

**Comment by robinvdvleuten** [comment]
Thanks for reporting this! What I did instead of rolling the PR back, is make it optional. So by default it uses the same behaviour as v2.6.0.
