### ISSUE TITLE
reducer not load data from local storage on refresh

### ISSUE THREAD

**Issue by mathias22osterhagen22** [robinvdvleuten/vuex-persistedstate#248]
- `vuex-persistedstate` version:  ^2.7.1 (demo on 
- `node` version: 10.16.3
- `npm` (or `yarn`) version: 6.13.6

**Relevant code or config  + What you did:**

_I tried:_
```javascript
plugins: [
    createPersistedState({
      reducer: state => state.user.age //state user age will not be load from local storage on refresh
    })
  ],
```
_And:_ 
```javascript
plugins: [
    createPersistedState({
      reducer: state => ({state: { user: {age: state.user.age}}}) //state user age will not be load from local storage on refresh
    })
  ],
```

**What happened:**

![image](https://user-images.githubusercontent.com/60438474/74222800-8e650c80-4cb5-11ea-881a-f00ca31f234e.png)

**Reproduction sandbox:**
_With reducer;_
[https://codesandbox.io/embed/vuex-persistedstate-k16dg](https://codesandbox.io/embed/vuex-persistedstate-k16dg)
_Without reducer:_
[https://codesandbox.io/s/vuex-persistedstate-qsh0o](https://codesandbox.io/s/vuex-persistedstate-qsh0o)

**Problem description:**
No loading the user.age when I refresh the page if I use the reducer method

I tried to add getters to see if it trigger something: 
[https://codesandbox.io/s/vuex-persistedstate-jh9g6](https://codesandbox.io/s/vuex-persistedstate-jh9g6)

But still not working. Is there something to do to make it load it automatically?

**Comment by mathias22osterhagen22** [comment]
Ok fixed by removing the "state" object according to this answer there: 
[https://github.com/robinvdvleuten/vuex-persistedstate/issues/63#issuecomment-347156754](https://github.com/robinvdvleuten/vuex-persistedstate/issues/63#issuecomment-347156754)
```js
reducer: state => ({
        count: state.count,
        user: {
          age: state.user.age
        }
      })
```

Please make some effort [about your API description](https://github.com/robinvdvleuten/vuex-persistedstate/issues/182#issue-406873954), provide some minimal example. You make your users passing their time to search for minimal code in your issues.

**Comment by saroshali4** [comment]
@mathias22osterhagen22 Hi, I could not get your solution. I'm doing the same thing but my data gets lost on refresh.
` reducer: state => ({
selectedPipeline: state.pipeline.selectedPipeline
})
`

Any help would be appreciated. Thanks

**Comment by saroshali4** [comment]
@mathias22osterhagen22 Hi, I could not get your solution. I'm doing the same thing but my data gets lost on refresh.
reducer: state => ({ selectedPipeline: state.pipeline.selectedPipeline })

I'm using modules in store.

Any help would be appreciated. Thanks
