### ISSUE TITLE
Hello, vuex-persistedstate minimum compatible ie what version?Thank you

### ISSUE THREAD

**Issue by left-handed** [robinvdvleuten/vuex-persistedstate#253]

**Comment by robinvdvleuten** [comment]
Should be IE11 but depends on your webpack / babel setup.

**Comment by oscbt** [comment]
Hi, I met a problem with vuex-persistedstate and IE11.
When I deploy nuxt app, IE11 said "Syntax Error" and IE detects arrow function.
I added vuex-persistedstate to transpile in nuxt.config.js, and app runs well
