### ISSUE TITLE
Persist Map objects properly

### ISSUE THREAD

**Issue by fogx** [robinvdvleuten/vuex-persistedstate#256]
Like in #210 hinted at, the vuex-persistedstate is not able to store Map objects inside the localStorage. They instead get saved as empty objects, because they can't be serialized directly with `JSON.stringify()`. These  [(1)](https://stackoverflow.com/questions/43704904/how-to-stringify-objects-containing-es5-sets-and-maps) [(2)](https://stackoverflow.com/questions/28918232/how-do-i-persist-a-es6-map-in-localstorage-or-elsewhere) SO Threads talks about this issue. The main issue is that Maps are capable of storing the order of insertion, which should be kept when persisted.

One option is [this answer](https://stackoverflow.com/a/28918362/6825464), which uses
`localStorage.myMap = JSON.stringify(Array.from(map));`
to deserialize 
and
`map = new Map(JSON.parse(localStorage.myMap));`
to serialize

on Map objects with serializable keys and values (everything else wouldn't work in JSON/ Local storage anyway. Might need a disclaimer though)

Another solution might be to use [this repo](https://github.com/jlipps/mapify), although im not sure if it catches anything that the previous method does not handle.

- `vuex-persistedstate` version:
2.7.1
- Yarn version: 
  1.22.0
- Node version: 
  13.10.1

Relevant code or config

state.js:
```javascript
export default{
example : new Map()
};
```

Reproduction sandbox:
I tried to add a sandbox, but i can't get [codesandbox.io](https://codesandbox.io/s/vuex-persistedstate-x0446) to recognize Map.set(). So here is a [JSfiddle](https://jsfiddle.net/18Lfzhan/) with the code, just not with the vuex-persistedstate.

**Comment by fogx** [comment]
https://github.com/jlipps/mapify

this might be a good solution

**Comment by fogx** [comment]
?

**Comment by robinvdvleuten** [comment]
I'm not gonna add support for Maps to the plugin, but you can easily do it yourself with a custom storage instance as mentioned in the README (https://github.com/robinvdvleuten/vuex-persistedstate#customize-storage).
