### ISSUE TITLE
Typescript subscriber how to use it ?

### ISSUE THREAD

**Issue by AsuraLuo** [robinvdvleuten/vuex-persistedstate#260]
const store = new Vuex.Store({
  state: {
    count: 0
  },
  plugins: [createPersistedState({
    key: 'magento_pwa_vue',
    storage: window.localStorage,
    fetchBeforeUse: true,
    reducer: (state) => {
      return {
        count: state.count
      }
    },
    subscriber: (store) => {
      return (mutation, state) => {
        console.log(mutation)
      }
    }
  })],
  mutations: {
    increment: state => state.count++,
    decrement: state => state.count--
  }
});

subscriber is error, please give a simple example ?

**Comment by robertgr991** [comment]
What are you trying to achieve with that subscriber? If you just want to add a new handler to the Vuex store, you should add it to the store with:
```javascript
store.subscribe((mutation, state) => {
  console.log(mutation)
})
```
The subscriber method used by the plugin is used to register the handler that has the logic to set the state after every mutation and it's a mere combination of some other options you provide.
```javascript
// node_modules/vuex-persistedstate/src/index.ts
function subscriber(store) {
  return function (handler) {
    return store.subscribe(handler);
  };
}
// Some other code
(options.subscriber || subscriber)(store)(function (mutation, state) {
  // This is their handler
  if ((options.filter || filter)(mutation)) {
    (options.setState || setState)(
      key,
      (options.reducer || reducer)(state, options.paths),
      storage
    );
  }
});
```
If you want to override this handler, although I don't see why would you, you can do something like this:
```javascript
subscriber: store => handler => {
  const myHandler = (mutation: MutationPayload, state: State) => console.log(mutation);
  store.subscribe(myHandler);
}
```
