### ISSUE TITLE
Is it possible to add just specific modules to the persisted state? 

### ISSUE THREAD

**Issue by cervoneluca** [robinvdvleuten/vuex-persistedstate#262]
I have a store whit several modules. 

this is a snapshot of it

```javascript
export default new Vuex.Store({
  plugins: [createPersistedState()],
  modules: {
    ui,
    account,
  },
  state: {
    isLoading: true,
  },
  mutations: {
  },
  actions: {
  },
});
```

I want to add only the "account" store to the persisted state. 
How can I accomplish this? 

Thank you!

**Comment by robinvdvleuten** [comment]
Have you tried reading the README at all? Please see the `path` options.
