### ISSUE TITLE
3.0.1 breaks version compatibility

### ISSUE THREAD

**Issue by nbubna** [robinvdvleuten/vuex-persistedstate#263]
Commit d9ce981 replaces the 3 parameters with 1 options parameter. That's a breaking change and you dropped it in a minor version release, breaking semver protocol.

**Comment by robinvdvleuten** [comment]
The options parameter did already exists with the corresponding options, so nothing changed there. The other two were not meant to be used anyway. So this was really a one minute fix if you were not using the options object as intended.

**Comment by nbubna** [comment]
"The other two were not meant to be used". Then they shouldn't have been there. Or at least been highlighted as inappropriate, because whether you like it or not, ease of fixing a public facing feature does not excuse breaking user's builds in a PATCH release. https://semver.org/

NPM practice when you install a lib is to use ^x.y.z, not x.y.z. That means that PATCH releases should *never* intentionally break compatibility. Versioning is meaningful, not just about how you feel. Now, if you insist that was an undocumented, ill-advised feature to use, you should at least have made it a MINOR release, claiming it was removing a long-deprecated (though it wasn't documented as such) API with easy fix for users.  But doing it as a PATCH release is just wrong, sorry.
