### ISSUE TITLE
Why using encrypted storage ?

### ISSUE THREAD

**Issue by b3j0f** [robinvdvleuten/vuex-persistedstate#268]
Hello, I have a question.

Why do you propose to encrypt data in local storage such as an example ?

I am not sure but if someone have an access to your local storage, it means he has access to the encrypted storage binding, and so, can get decrypted messages. Am I wrong ?

**Comment by b3j0f** [comment]
I discovered this library save keys thanks to a constant metakey...

Tell me if it sounds great to share this unsecured library.

**Comment by robinvdvleuten** [comment]
I don't propose to encrypt LocalStorage, I even think it's a very bad practice. But some people asked questions about it, so I've mentioned it in the README.
