### ISSUE TITLE
When to support asynchronous operations, such as indexdb?

### ISSUE THREAD

**Issue by wenfangcao** [robinvdvleuten/vuex-persistedstate#274]
- `vuex-persistedstate` version:
- `node` version:
- `npm` (or `yarn`) version:

Relevant code or config

```javascript
```

What you did:

What happened:

Reproduction sandbox:

Problem description:

Suggested solution:

**Comment by robinvdvleuten** [comment]
If you send in a PR with this async functionality, I'll consider it.
