### ISSUE TITLE
Is there a way to persist on every mutation?

### ISSUE THREAD

**Issue by rfox12** [robinvdvleuten/vuex-persistedstate#276]
I have a very small set of information that is mission-critical to my application (e.g. it's version number).  Is there a way to make vuex-persistedstate store the state on every "set" mutation?

**Comment by robinvdvleuten** [comment]
This does not like an issue but more of a question. Please move any question to StackOverflow or any Vue related forum.

**Comment by rfox12** [comment]
So you don't use issues for feature requests?

**Comment by robinvdvleuten** [comment]
This isn't a feature request, it's just a question. If you have a feature request, please create a PR containing the feature.
