### ISSUE TITLE
Page breaks when trying to display in an iframe from another domain.

### ISSUE THREAD

**Issue by juliomotol** [robinvdvleuten/vuex-persistedstate#284]
- `vuex-persistedstate` version: 3.0.1
- `node` version: 10.x
- `npm` (or `yarn`) version: not sure (im running the CD via GitHub Actions)

### Relevant code or config

```
plugins: [
    createPersistedState({
        key: 'some-key',
        paths: ['module1']
    })
]
```

### What you did:

I tried displaying the page that uses `vuex-persistedstate` in an iframe from another domain.

### What happened:

It thrown this exception (for obvious security reasons):

![image](https://user-images.githubusercontent.com/21353103/85735213-18c37f80-b730-11ea-9786-279ca35706d7.png)

And it broke the page preventing it form rendering further.

### Reproduction sandbox:

See fiddle [here](https://jsfiddle.net/6uwfca2j/).

### Suggested solution:

This should gracefully fail and not break the rendering of the Vue templates.

**Comment by robinvdvleuten** [comment]
This is out of scope for the plugin and has to do with access of your embedded iframe to the page's localstorage. If this is still an issue, please ask it on Stackoverflow or Vuejs forum.

**Comment by quannt** [comment]
@juliomotol We had the same issue and worked around by doing 

```
const persistState = createPersistedState({
  })


export default new Vuex.Store({
  strict: process.env.NODE_ENV === 'development',
  modules: {
    search,
    setting,
    error,
    booking,
    membership,
    facebook,
    extras
  },
  plugins: isLocalStorageAvailable ? [persistState] : []
})
```

@robinvdvleuten Yeah but the part that accesses local storage is abstracted away by vuex-persistedstate, it would be nice if the plugin could handle it, simply checking `window && window.localStorage` doesn't cut it anymore, the localStorage object is there but the iframes cannot use it.

**Comment by robinvdvleuten** [comment]
It is not abstracted away, you could easily overwrite it with a custom storage instance yourself (https://github.com/robinvdvleuten/vuex-persistedstate#customize-storage).

**Comment by juliomotol** [comment]
Upon checking the sandbox I sent here, it seems to have been fixed. Maybe there might have been a problem with the previous build of the site or it was an old browser version problem.
