### ISSUE TITLE
Cookie expiry date/time keeps resetting to the current date/time

### ISSUE THREAD

**Issue by imi47** [robinvdvleuten/vuex-persistedstate#285]
Hi. I'm using Nuxt.js and I have three Vuex files. One is the main index.js file and there are two other Vuex modules. I am try to make persist.js module persistent by using cookie. Persistence works, but I've noticed that any state change in any Vuex file causes the cookie expiry date/time to be set to to the current date/time. Even if the cookie doesn't exist yet, any state change in any Vuex file causes the cookie to be created.

I have added localStorage.js file (vuex-persistedstate config file) as a plugin in nuxt.config.js by doing:
 ` plugins: [
    { src: '~/plugins/localStorage.js', mode: 'client' },
]`

The code in localStorage.js file:
```
import createPersistedState from 'vuex-persistedstate'
import Cookies from 'js-cookie'

export default ({ store }) => {
  createPersistedState({
    paths: ['persist'],
    storage: {
      getItem: key => Cookies.get(key),
      setItem: (key, value) => Cookies.set(key, value, { expires: 3, secure: false }),
      removeItem: key => Cookies.remove(key)
    }
  })(store)
}
```

- `vuex-persistedstate` version: 3.0.1
- `node` version: 14.4.0
- `npm` (or `yarn`) version: 6.14.5

Am I doing something wrong?

**Comment by robinvdvleuten** [comment]
Everytime the state is changed, a new cookie is created with a new expiration date (and thus overwriting the current cookie). This issue lays in your application and not this plugin. If you need any additional help, please ask it on either Stackoverflow or Vuejs forum.
