### ISSUE TITLE
'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.

### ISSUE THREAD

**Issue by webcoderkz** [robinvdvleuten/vuex-persistedstate#286]
version: `"vuex-persistedstate": "^3.0.1"`

From a README:

```js
const dataState = new createPersistedState({
  paths: ['data']
})
```

but this causes an error in TS: `'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.ts(7009)`

![image](https://user-images.githubusercontent.com/5739191/86531820-5077b780-bee6-11ea-8219-305d4b1eecb4.png)

**Comment by robinvdvleuten** [comment]
This is an error in the README; you can create a plugin instance through `createPersistedState()`.

**Comment by webcoderkz** [comment]
@robinvdvleuten would you fix it, so others won't face this issue?

**Comment by robinvdvleuten** [comment]
@webcoderkz it is already fixed in the README 👍
