### ISSUE TITLE
possible to keep multiple tabs in sync

### ISSUE THREAD

**Issue by dan-yave** [robinvdvleuten/vuex-persistedstate#287]
Hi
just starting working with your library - all good no complaints, however I'm wondering if its possible to make changes to localstorage reactive as well. So for example i have two tabs open to the same page. On load they are in sync but a change to one tab does not get noticed by the second tab, even though inspecting local storage i see the change is in both tabs (as expected) - just not picked up by vue

-- vue: 2.6.11
- `vuex-persistedstate` version: 3.0.1

Suggested solution: possible to add a event listener to 'storage' that could trigger a change in vuex 

Thanks

**Comment by gangsthub** [comment]
I like the idea!

**Comment by gangsthub** [comment]
@robinvdvleuten Added a draft PR with a simple implementation.

**Comment by dan-yave** [comment]
Thank you @gangsthub !

**Comment by robinvdvleuten** [comment]
@gangsthub @dan-yave thank you both for the idea and effort! I like the idea of syncing between tabs and it is already quite easily to implement using event listeners outside of the scope of the plugin. 

The problem I see though, when the plugin implements this feature is that your application's state suddenly changes without any notification or possibility to filter / hook into the logic. What if you want to persist your complete state but only sync a couple of values between tabs for example. This means that also probably a lot of functionality needs to be replicated for both persisted state and synchronized state. 

I like the idea of single purpose plugins / functions. So it would be better to move such functionality off to something like a `vuex-synchronizedstate` plugin. But feel free to give your opinion on the topic.

**Comment by gangsthub** [comment]
I'll follow your advice, Robin. It could lead to strange UX sometimes if we sync the whole stored state, I agree.

What about, instead of [`syncTabs`](https://github.com/robinvdvleuten/vuex-persistedstate/pull/289/files#diff-f41e9d04a45c83f3b6f6e630f10117feR27) being a `boolean`, we pass an array of something like `paths`, or "deep paths" (in "dot notation" to be consumed by [shvl](https://github.com/robinvdvleuten/shvl)) and update only the selected "leaves" of the state tree?

**Comment by gangsthub** [comment]
Giving this a second thought... maybe you're right, "persistedstate" shouldn't also do "syncstate"... Maybe this is an opportunity for another plugin to be born and coexist with this one... I'm going to close the PR ;)

Thanks, Robin

**Comment by Heziode** [comment]
Hi,

Any progress on this feature ?
Did you will add this feature in `vuex-persistedstate` or create a special plugin that will work along side with this ?

**Comment by robinvdvleuten** [comment]
@Heziode feel free to create a plugin yourself.
