### ISSUE TITLE
Will it sync store between tabs?

### ISSUE THREAD

**Issue by terion-name** [robinvdvleuten/vuex-persistedstate#29]
Hi. Will this plugin sync store between tabs? I mean, if an app is opened in two tabs, I commit something to vuex, it is pushed to localstore, will the vuex in second tab catch it up?

**Comment by robinvdvleuten** [comment]
@terion-name please see issue #28. This isn't related to this plugin, but to the working of the localStorage API. Please check StackOverflow or similar in the future, but here seems to be a working gist for now => https://gist.github.com/tomasperezv/5175824

**Comment by terion-name** [comment]
@robinvdvleuten I know how to implement this via localStorage api, my question was is this functionality shipped with the plugin :) so the answer is no, thank you.

I think, that it would be great to consider adding this to the plugin, it will suite good here
