### ISSUE TITLE
createPersistedState not retaining store module state (NuxtJS)

### ISSUE THREAD

**Issue by davydelbeke** [robinvdvleuten/vuex-persistedstate#293]
- `vuex-persistedstate` version: 3.0.1
- `node` version: v13.5.0
- `npm` (or `yarn`) version: 6.13.4

I'm writing my first nuxt.js site and the plugin is not saving the data from my cart module. This is my code (I've collapsed irrelevant code)

plugins/localStorage.js
```
import createPersistedState from 'vuex-persistedstate'
import SecureLS from 'secure-ls'

let ls = new SecureLS({ isCompression: false })

export default async ({
  app, store, $axios, isHMR,
}) => {
  // Just in case nuxt.config.js gets a change in ssr:false when adding this plugin.
  // Notice isClient is deprecated, instead use process.browser.
  if (process.browser) {
    // In case of HMR, mutation occurs before nuxtReady, so previously saved state
    // gets replaced with original state received from server. So, we've to skip HMR.
    // Also nuxtReady event fires for HMR as well, which results multiple registration of
    // vuex-persistedstate plugin
    if (isHMR) return
    createPersistedState()(store) // vuex plugins can be connected to store, even after creation
  }
}
```

plugins/localStorage.js
```
import Vuex from 'vuex';
import Cart from '~/store/cart'    
let store
    
const initStore = () => {
  return store || (store = new Vuex.Store({
    state: {
      status: '',
      token: '',
      tokensExpiry: '',
      tokensExpiryDate: '',
      user: ''
    },
    mutations: { ... },
    actions: { ... },
    getters: { ... },
    modules: {
      cart: Cart
    }
  }))
}

export default initStore
```

store/cart.js
```
export const state = () => ({
  pledges: [],
  deliveryMethod: []
})

export const mutations = { ... }

export const getters = { ... }

export default {
  state,
  mutations,
  actions,
  getters
};
```

nuxt.js
```
...
plugins: [
    { src: '~/plugins/localStorage.js', ssr: false }
],
...
```

The plugin has no trouble storing everything from my `store/index.js` but all data from `store/cart.js` is lost after every refresh.

**Comment by mishingo** [comment]
same issue here

**Comment by xeno** [comment]
Same, with a similar setup. I'm running nuxt ^2.13.0, and this only started happening after I updated to 2.13.

**Comment by xeno** [comment]
After further research, it seems `this.$store.state` is not persisted on initial load. The state does end up being re-hydrated, as vuex' mapState function can still populate variables. It also seems to be tripping up Vue tools, at least in Firefox.

**Comment by xeno** [comment]
I've created the following test repository to demonstrate the issue: [https://github.com/xeno/persist-issue](https://github.com/xeno/persist-issue)

1. Run this, put something into the initial form.
2. When the page changes, both values on the page will be populated.
3. Reload the page.
4. Outcome: the initial state does not populate

**Comment by salismt** [comment]
same issue, this is prevailing especially for creating authentication middleware where you get the token from vuex store.
I have even tried storing the token both in vuex store (this library) along with saving to cookies. It's not able to get the token during middleware function call

**Comment by Jemaz** [comment]
I should add that Nuxt has deprecated `SSR` for `mode`.

You can see it here: https://nuxtjs.org/guide/plugins/#object-syntax

so it should be, in theory,  
`plugins: [{ src: '~/plugins/localStorage.js', mode: 'client' }]`

And it's working. However, only my module for `app.js` (I believe it's connected to @davydelbeke problem that it's the same for `index.js`) doesn't persist.

**Comment by Santieherrero** [comment]
I have several nuxtjs sites and I work with Cookies for user sessions and LocalStorage for other stuff and this code works for me.

I'm getting the token with middleware cookie from nuxt server, I leave below the code that I use

plugins/storage.js
```
import ...
const userCookiePaths = [
  'user.accessToken',
  'user.expiresAt',
  'user.email',
  ...
]
const userStoragePaths = ['user.organizations']

export default ({ store }) => {
  const cookieStoreConfig = {
    key: 'cookieStore',
    paths: userCookiePaths,
    storage: {
      getItem: (key) => {
        return Cookies.getJSON(key)
      },
      setItem: (key, value) => {
        return Cookies.set(key, value, { expires: 3, secure: false })
      },
      removeItem: (key) => {
        return Cookies.remove(key)
      },
      fetchBeforeUse: true,
    },
  }

  const appStoreConfig = {
    key: 'appStore',
    paths: userStoragePaths,
    storage: {
      getItem: (key) => ls.get(key),
      setItem: (key, value) => {ls.set(key, value)},
      removeItem: (key) => ls.remove(key),
    },
  }

  window.onNuxtReady(() => {
    createPersistedState(cookieStoreConfig)(store)
    createPersistedState(appStoreConfig)(store)

    // Restore cookie state
    const savedState = Cookies.getJSON(cookieStoreConfig.key)
    if (typeof savedState === 'object' && savedState !== null) {
      const data = merge(store.state, savedState, {
        arrayMerge: (store, saved) => {
          return saved
        },
        clone: false,
      })
      store.dispatch('user/restoreUser', data.user)
    }

    // Restore local storage state
    let localData = ls.get(appStoreConfig.key)
    if (localData) {
      localData = JSON.parse(localData)
    }
    if (typeof localData === 'object' && localData !== null) {
      // Update user because restore wipe all data from cookies
      store.dispatch('user/updateUser', localData.user)
    }
  })
}
```
middleware/auth.js
```
isAuthUserFromServer = (req, store) => {
  const cookie = require('cookie')
  if (req.headers.cookie) {
    let storeCookie
    try {
      const savedState = JSON.parse(
        cookie.parse(req.headers.cookie).cookieStore
      )
      if (typeof savedState === 'object' && savedState !== null) {
        const data = merge(store.state.user, savedState.user, {
          arrayMerge: (store, saved) => {
            return saved
          },
          clone: false,
        })
        storeCookie = data
        store.dispatch('user/restoreUser', data)
      }
    } catch (error) {
      return false
    }

    if (hasAuthorization(storeCookie)) {
      return true
    }
   ....
}

export default ({ store, redirect, route, req }) => {
  if (process.server) {
    if (isAuthUserFromServer(req, store)) {
      if (route.path === '/session') {
        return redirect('/')
      } else {
        return
      }
    } else {
      return redirect('/session')
    }
  }
```

I hope that this code can help you, sure there is a better way for this approaching!

**Comment by FreekVR** [comment]
I believe I've found a solution that works for reading the state correctly server-side, without too many changes. It expands on the Cookies example in the README, but expands it to work server-side (js-cookie only works with a `window` object). If for some reason you're also _setting_ or _deleting_ cookies on the server-side, you'd need to use `cookie.serialize` and modify `req.headers` as well, but that's not a use case for us so decided to skip that.

First, you'll need to add the server-side `cookie` AND client-side `js-cookie` package. Eg. `yarn add cookie js-cookie`

Then, add a `~/plugins/persist-state.js` file with the following (make sure to adjust the paths and other options to your needs):

```js
import createPersistedState from 'vuex-persistedstate';
import * as Cookies from 'js-cookie';
import cookie from 'cookie';

export default ({ store, req }) => {
    createPersistedState({
        paths: ['preferences'],
        storage: {
            getItem: (key) => {
                if (process.server) {
                    const parsedCookies = cookie.parse(req.headers.cookie);
                    return parsedCookies[key];
                } else {
                    return Cookies.get(key);
                }
            },
            // Please see https://github.com/js-cookie/js-cookie#json, on how to handle JSON.
            setItem: (key, value) =>
                Cookies.set(key, value, { expires: 3, secure: false }),
            removeItem: key => Cookies.remove(key)
        }
    })(store);
};
```

Then, add it to your `nuxt.config.js`:

```js
plugins: [
   '~/plugins/persist-state.js'
];
```

Perhaps this would be good to add to the README as well @robinvdvleuten

**Comment by robinvdvleuten** [comment]
@FreekVR feel free to add your example to the README through a PR. Best place would be below the current Nuxt.js setup.

**Comment by robinvdvleuten** [comment]
As the README now contains a solution, this can be closed.
