### ISSUE TITLE
Deleting items from persisted array 

### ISSUE THREAD

**Issue by steve-tek** [robinvdvleuten/vuex-persistedstate#31]
I'm having an issue forcing deleted array items persist.  It seems the new array is just merged to the old array rather than replacing it in the mutation function.  Is there a specific way you need to delete items from the array?  I'm able to change values and make those persist fine.

Thanks!

**Comment by robinvdvleuten** [comment]
@steve-tek this is indeed the default functionality. As some developers want their array merged and some of them want to have their array replaced. You can easily add this to your plugin instance by overriding one of the API methods (https://github.com/robinvdvleuten/vuex-persistedstate#createpersistedstateoptions). You can read more about this philosophy in [this comment](https://github.com/robinvdvleuten/vuex-persistedstate/issues/32#issuecomment-311272320).
