### ISSUE TITLE
    "vue": "^2.6.11",    "vuex": "^3.4.0",    "vuex-persistedstate": "^3.1.0",  Not working properly

### ISSUE THREAD

**Issue by zhangwenwu** [robinvdvleuten/vuex-persistedstate#313]
import createPersistedState from 'vuex-persistedstate'

Vue.use(Vuex)

const store = new Vuex.Store({
  modules: {
    user
  },
  getters,
  plugins: [
    createPersistedState()
  ]
})

**Comment by robinvdvleuten** [comment]
Do you have a codesandbox for this to reproduce?
