### ISSUE TITLE
Hide/change vuex key ls.

### ISSUE THREAD

**Issue by uwejan** [robinvdvleuten/vuex-persistedstate#318]
Hi. Am using latest version of npm and vuex-persistedstate.
![gnome-shell-screenshot-YODAQ0](https://user-images.githubusercontent.com/20250935/91060174-4d21c200-e633-11ea-9b2f-3aeeaec3e9e0.png)
The image shows that on my localStorage tab on dev console. there is `vuex` key, i was wondering if there is a way to change it.
Thanks.

**Comment by robinvdvleuten** [comment]
Just pass in a different key name as option when creating a new plugin instance.

```js
import createPersistedState from 'vuex-persistedstate'

export default ({store}) => {
  createPersistedState({
    key: 'customkey',
  })(store)
}
```
