### ISSUE TITLE
unhandled json parsing exceptions

### ISSUE THREAD

**Issue by gaborcorp** [robinvdvleuten/vuex-persistedstate#32]
Noticed that json parsing exception are not handled. if the value is not proper json will end up in:
Uncaught SyntaxError: Unexpected token in JSON 

I guess it might be handled later on, but does break the example

https://github.com/robinvdvleuten/vuex-persistedstate/blob/9d79a3e09d63c442b83ee70a6aaeb33726a23931/src/plugin.js#L59

**Comment by robinvdvleuten** [comment]
@gaborcorp it is indeed not handled by the plugin to keep the functionality of it by a minimum. But all core functionality is overridable, so you could add your own JSON parsing by overriding the `getState` method. 

The reason why I didn't add validation or other "extended" functionality is that everybody has a different opinion on how to handle those. By making the core functionality - persisting (partial) state into localstorage - just work, one can easily add their own functionality on top of it.

**Comment by gaborcorp** [comment]
I'd still argue that you probably should handle exceptions raised by your own code (or at least somehow be transparent that it must be done) and then if people disagree in the way you recover they can override that.

Currently if there is an error than it will break your application through the unhandled error which I don't think is anyone's default choice.
