### ISSUE TITLE
Change in main state resets the cookie expiry date of module's state which is being persisted

### ISSUE THREAD

**Issue by imi47** [robinvdvleuten/vuex-persistedstate#320]
- `vuex-persistedstate` 3.1.0:
- `node` 14.8.0:
- `npm` version: 6.14.7

I am persisting the state of a Vuex module in cookie with an expiry date. The problem is that any change in the main state causes the expiry date to reset to the current date. (This should only happen if there is a state change in the module only.)

Please check out the reproduction sandbox:
https://codesandbox.io/s/boring-butterfly-fv3qs?file=/src/App.vue

A note about the sandbox: For me the state was not being preserved at all on Chrome, even with the official sandbox example. It is working on Firefox but it has the aforementioned issue.

Thanks.

**Comment by robinvdvleuten** [comment]
Everytime the state is changed, a new cookie is created with a new expiration date (and thus overwriting the current cookie). This issue lays in your application and not this plugin. If you need any additional help, please ask it on either Stackoverflow or Vuejs forum.
