### ISSUE TITLE
How to use in vue2-typescript and vue-class, vuex-module-decorators

### ISSUE THREAD

**Issue by gebilaofan** [robinvdvleuten/vuex-persistedstate#321]
- `vuex-persistedstate` version:3.1.0
- `node` version: 11.15.0
- `npm` (or `yarn`) version:6.7.0

Relevant code or config

```javascript
```

What you did:
I want to use it in the vue+ts project. Is it because of how I use it?

I now have a user module, the code is as follows
```javascript

import { VuexModule, Module, Mutation } from 'vuex-module-decorators'
@Module({ namespaced: true })
class User extends VuexModule {
  public isLogin: boolean = false   // 是否登录
  
  @Mutation
  public setIsLogin(data: boolean): void {
    this.isLogin = data
    console.log("User -> setIsLogin -> isLogin", this.isLogin)
  }

}

export default User

```

Then introduce it in the index
```javascript
import Vue from 'vue'
import Vuex from 'vuex'
import User from '@/store/modules/user'
import TIMMessage from '@/store/modules/TIMMessage'
import TIMGroup from '@/store/modules/TIMGroup'
import createPersistedState from "vuex-persistedstate"

// 初始化 Vuex 并注册此模块
Vue.use(Vuex)

const store = new Vuex.Store({
  modules: {
    user: User
  },

})

export default store

```

How to put the state in the user module into the plugin？？？

What happened:

I tried to use it directly, but it directly saves all my data, which is not the result I want  :(
`plugins:[createPersistedState]`

Problem description:

Suggested solution:

**Comment by robinvdvleuten** [comment]
Please ask any questions on either StackOverflow or Vuejs forum please.
