### ISSUE TITLE
[docs needed ?] - vuex-persistedstate with vuexfire bindings

### ISSUE THREAD

**Issue by malomarrec** [robinvdvleuten/vuex-persistedstate#325]
This issue sits in-between a feature request and a request for more documentation.
It is not as well-defined as I'd like for an issue, but this felt like the best place to post it. If this is not the place, please indicate where it would make sense.

Are there best practices on how to setup `vuex-persistedstate` with `vuexfire`? I am encountering weird side effects when using vuex-persistedstate to persist a state defined by a vuexfire binding. Namely, the bindings  and/or store are refreshing erratically, resulting in old data and up to data data being blended together.

Are there any tips / best-practices? Is this discouraged? Is this a use case common enough to grant a docs section?

*Use case*
Persist a vuexfire data and binding across page navigation and reload. 

*Context*
- "vuex-persistedstate": "3.1.0",
 - "vuexfire": "3.2.4"

In store/modules/project.js
``` export default {
  namespaced: true,
  state: {
    projected,
    project: {}
  },
  actions: {
    bindProject: firestoreAction(({ state, bindFirestoreRef }) => {
      return bindFirestoreRef('project', fb.katasCollection.doc(state.projectId))
      }),
  },
```

In store/index.js
```
Vue.use(Vuex)
// import createPersistedState from "vuex-persistedstate";

export const store = new Vuex.Store({
  plugins: [
    createPersistedState({
      paths: ['project'],
    }),
  ],
  mutations: {
    ...vuexfireMutations,
  },
  modules: {
    project: project
  }
})
```

**Comment by robinvdvleuten** [comment]
I am not a Vuexfire user so I can't help you with this. Please ask your question on either Stackoverflow or the Vuejs forum.
