### ISSUE TITLE
Vue3.0 support

### ISSUE THREAD

**Issue by jahnli** [robinvdvleuten/vuex-persistedstate#343]
Could you tell me the author Do you plan to support Vue3.0 and when do you expect to implement it

**Comment by robinvdvleuten** [comment]
@jahnli the plugin itself doesn't use anything related to Vue, so Vue 3.0 is supported out of the box. It does use Vuex, so I made the plugin compatible with Vuex 4.0.

Please install version `4.0.0-beta.1` of this plugin to use it with Vuex 4.0.
