### ISSUE TITLE
improve NuxtJS usage instructions

### ISSUE THREAD

**Issue by fabiom91** [robinvdvleuten/vuex-persistedstate#354]
- `vuex-persistedstate` version: "^4.0.0-beta.1"
- `node` version: v11.13.0
- `npm` (or `yarn`) version: npm 6.7.0

**nuxt.config.js** plugins:

```javascript
plugins: [{ src: '~/plugins/persistedState.client.js' }],
```

`plugins/`**persistedState.client.js**

```javascript
import createPersistedState from 'vuex-persistedstate'

export default ({ store }) => {
  createPersistedState({
    key: 'current_session',
    paths: '/',
  })(store)
}
```

`store/`**index.js**

```javascript
export const state = () => ({
  mySurveys: [],
})

export const mutations = {
  SET_MY_SURVEYS(state, surveys) {
    state.mySurveys = surveys
  },
}
```

What you did:
I followed the Readme to configure client side plugin for NuxtJS by creating a new plugin called `persistedState.client.js` and adding the plugin in `nuxt.config.js` as above.

What happened:
No error but when I reload the page, the data pulled from the Vuex storage disappear as usual.

Problem description:
I followed the Nuxtjs part of the readme but the Vuex storage is still ignoring the plugin. I believe I'm missing something but I can't find further info in the documentation. So after setting up the plugin, what do I need to do to make sure that if I reload a page that is using data from Vuex storage, keep using the data?

Suggested solution:
Please improve readme.

**Comment by fabiofdsantos** [comment]
Paths must be specified using dot notation.

Examples: 
 - store/surveys.js `['surveys']`
 - store/anything/surveys.js `['anything.surveys']`

**Comment by fabiom91** [comment]
> Paths must be specified using dot notation.
> 
> Examples:
> 
> * store/surveys.js `['surveys']`
> * store/anything/surveys.js `['anything.surveys']`

Thanks Fabio, It worked! :)
