### ISSUE TITLE
Storage bug after reload

### ISSUE THREAD

**Issue by AlennGK** [robinvdvleuten/vuex-persistedstate#36]
I don't know if this is the browser, workspace or problem of your plugin and I am going crazy.
After page refresh ... mostly I am not able to change some values by calling mutation, but some of them works fine.

If you have [time](https://forum.vuejs.org/t/vuex-localstorage-stuck-persistedstate/13400) otherwise delete this, thank you =)

**Comment by 4iGAN** [comment]
Try changing your code from this 
```
destroyAuth() {
  state.auth = { status: false, token: '', exp: '' }
  state.user = { name: '', email: '', id: '' }
  console.log('Auth destroyed')
}
```
to this one:
```
destroyAuth(state) {
  state.auth = { status: false, token: '', exp: '' }
  state.user = { name: '', email: '', id: '' }
  console.log('Auth destroyed')
}
```
I think this can help.

**Comment by robinvdvleuten** [comment]
That's indeed the correct change in your code. You were missing the `state` argument there.
