### ISSUE TITLE
vue3.0版本无效

### ISSUE THREAD

**Issue by xushanpei** [robinvdvleuten/vuex-persistedstate#362]
import { createStore } from "vuex";
import home from './home/index';
import { GlobalState } from '../typings/layout';
import createPersistedState from "vuex-persistedstate";

const store = createStore<GlobalState>({
    modules:{
        home
    },
    plugins: [createPersistedState()]
})

export default store

刷新页面数据状态会自动变成初始化的值,不知道什么问题呢

请大佬解答

**Comment by robinvdvleuten** [comment]
Sorry I don't know what to make from this.
