### ISSUE TITLE
browser.storage support? 

### ISSUE THREAD

**Issue by rendomnet** [robinvdvleuten/vuex-persistedstate#363]
- `vuex-persistedstate` version: 3.0.1
- `node` version: v10.19.0
- `npm` (or `yarn`) version: 1.22.4

Problem description:
Fo Firefox and Web extensions we need to use 
browser.storage instead of Window.localStorage
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local

How can I use browser.storage with vuex-persistedstate?

**Comment by robinvdvleuten** [comment]
You can't. The browser.storage API is asynchronous, but the vuex-persistedstate expects synchronous storage.

**Comment by rendomnet** [comment]
@robinvdvleuten what about storage.sync
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync
