### ISSUE TITLE
vuex-persistedstate in nuxtjs didn't work with the indexjs modules

### ISSUE THREAD

**Issue by ericheshenghao** [robinvdvleuten/vuex-persistedstate#381]
- `vuex-persistedstate` version: 2.7.0
- `node` version:
- `npm` (or `yarn`) version:
- `nuxtjs` version:2.14.5

I have  code below as nuxtj plugins 
```
 plugins: [
    { src: '@plugins/persistedState.client.js', ssr: false }
  ],
```
the details:👇
```javascript
import createPersistedState from 'vuex-persistedstate'
// 前端数据持久化
export default ({ store }) => {
  window.onNuxtReady(() => {
    createPersistedState({
      key: 'state',

      paths: ['index', 'modules.collection', 'modules.doc', 'modules.user']
    })(store)
  })
}
```

What happened:

 **When I refresh the page, the module's data remains, but  th date in index.js  has been reloaded**

Suggested solution: I also want the data in indexjs to be remained,i have already search the questions , but cant find any resolution,could anyone help?😟

**Comment by solidevolution** [comment]
Same here

**Comment by robinvdvleuten** [comment]
This does not look like a bug with the plugin but with your application. Please ask for help on either StackOverflow or any Nuxt / Vue related forums.
