### ISSUE TITLE
How it use with Subdomains?

### ISSUE THREAD

**Issue by mrFANRA** [robinvdvleuten/vuex-persistedstate#396]
Hi! Thanks for you package!

How can I get one local storage for all my subdomains? Is it possible?

**Comment by Bacca2095** [comment]
Yes it's possible, only you need is provide a key `createPersistedState({ key: "subdomain_identifier" })`

**Comment by robinvdvleuten** [comment]
Please ask questions on either StackOverflow or any Vuejs related forum. The issue tracker is for issues only.
