### ISSUE TITLE
Add option to include or exclude paths

### ISSUE THREAD

**Issue by syropian** [robinvdvleuten/vuex-persistedstate#4]
Sometimes it's easier to exclude certain paths than to manually include a bunch. If you're busy I can take a crack at this and file a PR.

**Comment by robinvdvleuten** [comment]
Good suggestion @syropian! It's added in the v1.1.0 release. Please see the README for the _reducer_ function.

**Comment by RashadSaleh** [comment]
@robinvdvleuten Hello! Thanks for the cool plugin. Can you please elaborate on how this can work? An example would be excellent.

**Comment by robinvdvleuten** [comment]
Hi @RashadSaleh! You can see how the functionality works by looking at the `defaultReducer` in [plugin.js](https://github.com/robinvdvleuten/vuex-persistedstate/blob/master/src/plugin.js#L4). It's in its base just a simple JS reducer which returns an object containing all values you want to store.

**Comment by Edujugon** [comment]
@robinvdvleuten 
Is this the best approach for reducer function?
```
reducer: (state,paths) => {
                let reducer = Object.assign({},state);
                delete reducer.dates; // state which I don't want to persist.

                return reducer;
            }
```
Thanks in advance.

**Comment by robinvdvleuten** [comment]
@Edujugon please checkout the default reducer method [here](https://github.com/robinvdvleuten/vuex-persistedstate/blob/master/src/plugin.js#L4). It should look something like this in (in your case);

```js
reducer (state, paths) {
  // No need to use let as the reducer itself can be immutable which do not mean that the properties 
  are not mutable (https://ponyfoo.com/articles/var-let-const)
  const reducer = Object.assign({}, state);
  // state which you don't want to persist.
  delete reducer.dates;

  return reducer;
}
```

Much easier is it though to give an array of paths to persist as option (https://github.com/robinvdvleuten/vuex-persistedstate#createpersistedstateoptions)

**Comment by sedatsevgili** [comment]
Btw, if anyone uses vuex with namespaces and not to persist some key in any module, Object.assign is not enough. You have to deep clone your state.
