### ISSUE TITLE
question: ssr nuxt cookies & secure cookies

### ISSUE THREAD

**Issue by stephenjason89** [robinvdvleuten/vuex-persistedstate#403]
If i will be using cookies together with SSR, 
what are the performance implications of having cookies not only on the client side but also server side?
This is for an app that potentially be thousands of users, thus creating thousands of sessions each with cookies to the server.

Second question, Can I use secure cookies?

**Comment by robinvdvleuten** [comment]
When you have thousands of users using cookies, that won't be a performance bottleneck. You'll probably run sooner into issues with your database etc. 
To use secure cookies you need to have a SSL connection (https) with the server, this can be an issue in your local development environment.

**Comment by stephenjason89** [comment]
Thank you for taking the time to reply :)
