### ISSUE TITLE
Vue3.0 uses Vuex 4.0 to refresh the page after data loss

### ISSUE THREAD

**Issue by anpabupa** [robinvdvleuten/vuex-persistedstate#405]
- `vuex-persistedstate` version: ^4.0.0-beta.3

export interface StateInterface {
  // Define your own store structure, using submodules if needed
  // example: ExampleStateInterface;
  // Declared as unknown to avoid linting issue. Best to strongly type as per the line above.
  system: SystemStateInterface
  setting: {
    route: RouteStateInterface
    theme: ThemeStateInterface
  }
}

export default store(function (/* { ssrContext } */) {
  const Store = createStore<StateInterface>({
    modules: {
      system,
      setting,
    },

    strict: false,
    plugins: [
      createPersistedState({
        storage: window.sessionStorage,
        reducer: ({ system, setting }) => ({ system, setting }),
      }),
    ],
  })

  return Store
})

------My sessionstorage has values but the refresh page state is still reset

Excuse me, is there something wrong with the method I used

**Comment by atom-git** [comment]
use this.$store.state. system to get the value, Through a morning time analysis，found only in this model can get the correct result
