### ISSUE TITLE
Debounced setState a bad idea?

### ISSUE THREAD

**Issue by jaunt** [robinvdvleuten/vuex-persistedstate#406]
My app quite heavily writes to vuex at times, and since setState is calling json.stringify and writing to localstorage, is there any harm debouncing the final write until things settle? 

Here's an example of what I mean:

```
      setState: (key, state, storage) => {
        // debounce storing state
        if (persistTimer != null) {
          clearTimeout(persistTimer);
        }
        persistTimer = setTimeout(() => {
          storage.setItem(key, JSON.stringify(state));
          persistTimer = null;
        }, 100);
      },

**Comment by robinvdvleuten** [comment]
If writing to LocalStorage becomes a performance bottleneck, I would suggest revisiting your application architecture. I would definitely not recommend doing async writes to prevent state mismatch issues.
