### ISSUE TITLE
how can i use dynamic key

### ISSUE THREAD

**Issue by bestRenekton** [robinvdvleuten/vuex-persistedstate#418]
- `vuex-persistedstate` version:4.0.0-beta.3
- `node` version:15.1.0
- `npm` (or `yarn`) version:1.22.10

Relevant code or config

```javascript
createPersistedState({
key:'user1',
...
})
```

Problem description:
when user1 login, we save his data as 'user1' by localstorage
then he logout  and user2 login
so how can we save his data as 'user2' by localstorage ? we want their both data in localstorage,because user1 maybe login next time.

Suggested solution:
in vuex module , this can do work, but It's too cumbersome，because we have many module
```js
const state: userModuleState = {
  userInfo: {
    user1:{...}
     user2:{...}
   }
};
```
so can  vuex-persistedstate  set   dynamic key ?

**Comment by robinvdvleuten** [comment]
Please ask questions on either StackOverflow or any Vuejs related forum. The issue tracker is for issues only.

**Comment by paraself** [comment]
The issues is that the documentation does not demonstrate clearly how to change the prefix dynamically after the vuex store is instantiated and `createPersistedState` is called.
