### ISSUE TITLE
Not working with Secure-Ls

### ISSUE THREAD

**Issue by BonBonSlick** [robinvdvleuten/vuex-persistedstate#419]
- `vuex-persistedstate` version:     "vuex-persistedstate": "^4.0.0-beta.3",
- `node`  10.24:
- `npm` (or `yarn`) version: 1.22

Relevant code or config

```javascript
```

What you did:

What happened:
  
Problem description: old state, its never updated, changed. 

https://github.com/softvar/secure-ls/issues/56

So, custom STORAGE option could be broken, tested with  latest persistedstate and Securels, also some old version stopped to work.

**Comment by robinvdvleuten** [comment]
Could you at least provide a reusable example?

**Comment by NorseGaud** [comment]
@robinvdvleuten 

```
import { createStore } from 'vuex'
. . .
import createPersistedState from "vuex-persistedstate";
import SecureLS from "secure-ls";
const ls = new SecureLS({ isCompression: false });

export default new createStore({
  state: {
    count: 0
  },
  plugins: [
    createPersistedState({
      storage: {
        getItem: (key) => {
          console.log(key)
          ls.get(key)
        },
        setItem: (key, value) => ls.set(key, value),
        removeItem: key => ls.remove(key)
      }
    })
  ],
  modules: {
    xxxx,
    search
  }
});
```

Loading the page shows 

```
index.js:163 Uncaught Error: Could not parse JSON
    at SecureLS2.get (index.js:163)
    at Object.getItem (index.js?t=1631830051988:19)
    at n2 (index.ts:38)
    at s (index.ts:80)
    at index.ts:90
    at vuex.esm-bundler.js:935
    at Array.forEach (<anonymous>)
    at new Store2 (vuex.esm-bundler.js:935)
    at new createStore (vuex.esm-bundler.js:880)
    at index.js?t=1631830051988:10
```

And the console.log(key) shows a string of "vuex". 

Maybe related to https://github.com/robinvdvleuten/vuex-persistedstate/pull/400 ?
