### ISSUE TITLE
Lots of plugins?

### ISSUE THREAD

**Issue by igorpopryadukhin** [robinvdvleuten/vuex-persistedstate#426]
I do not know if there is an official communication channel, I would like to clarify the following question.

Is it possible to create multiple instances of a plugin this way?

![image](https://user-images.githubusercontent.com/48174353/128607692-ac9abc14-ed61-4e85-9de0-bd7ff61c7169.png)

![image](https://user-images.githubusercontent.com/48174353/128607866-9356d5dd-a55f-40b5-95a7-9c7861d9b710.png)

What are the contraindications?
How will this affect performance?

**Comment by robinvdvleuten** [comment]
This does not look like a bug with the plugin but with your application. Please ask for help on either StackOverflow or any Nuxt / Vue related forums.
