### ISSUE TITLE
VueDevtools not data

### ISSUE THREAD

**Issue by cheng-shuai** [robinvdvleuten/vuex-persistedstate#427]
- `vuex-persistedstate` version: `4.0`
- `node` version: `14.17.4`
- `npm` (or `yarn`) version: `yarn 1.22.1`

Relevant code or config

```javascript
import createPersistedState from 'vuex-persistedstate'
# and
  plugins: [createPersistedState()]

```

What you did: I reload page

What happened: Vue Devtools not data but in localStorage have data
![image](https://user-images.githubusercontent.com/60097799/131145379-b9ca1b5c-7a9d-46e2-93dc-a93cfb885108.png)
![image](https://user-images.githubusercontent.com/60097799/131145449-f7f8a4c5-0ba9-452a-b98a-30a6cd856697.png)

Reproduction sandbox:

Problem description: I reload page but VueDevtools not data, something wrong with me and what should i do ? thanks

Suggested solution:

**Comment by robinvdvleuten** [comment]
This does not look like a bug with the plugin but with your application. Please ask for help on either StackOverflow or any Nuxt / Vue related forums.
