### ISSUE TITLE
Issue after register module

### ISSUE THREAD

**Issue by disjfa** [robinvdvleuten/vuex-persistedstate#43]
So i mage a plugin for vue and am working on a demo project. So i wanted to add your localstorrage and it works awesome.

My plugin: https://github.com/disjfa/vue-route-timeline / https://disjfa.github.io/vue-route-timeline/
My template: https://github.com/disjfa/kazoo / https://disjfa.github.io/kazoo

The store gets persisted like it would, but my store module in my plugin is not updated with the store. I think it is because your store items gets set before the `store.registerModule(moduleName, timelineStore);` in my plugin gets called. So the state of my plugin gets reset.

You can check it out by clicking in my app and on the homepage the list grows. But on f5 it's cleaned again. It does gets stored in the localstorage by the way.

If i can help or know where to look i can help.

**Comment by alex-oleshkevich** [comment]
+1, got same issue

**Comment by dhax** [comment]
same issue here... any progress on this?

**Comment by agonzalezml** [comment]
+1

**Comment by robinvdvleuten** [comment]
Please read the note about [localForage](https://github.com/robinvdvleuten/vuex-persistedstate#️-localforage-️). A Vuex / Flux architecture and thereby this plugin cannot handle any asynchronous.

**Comment by agonzalezml** [comment]
Bad news

**Comment by robinvdvleuten** [comment]
@agonzalezml please not that it's not an issue with this plugin, it's an issue in how you guys want to use "asynchronously" in your Vuex store.

**Comment by disjfa** [comment]
Yup, i was also looking into this and how and where to trigger asynchronous mutations. But i can't find where to trigger those in vuex. It's not quite asynch, but just when we register new stores.

But you can easilly save local state of (your own) plugins using localstorrage, that's just some extra lines of code.

**Comment by robinvdvleuten** [comment]
what about loading your "persisted state" asynchronously before creating the store instance?

**Comment by disjfa** [comment]
Thats not the issue. The issue is vuex logics.

1. serup app store
1.1 connect your persistedstate on main store state
2. register plugin which resisters own module in the state.

And thus the persisted store is already registered and written so the modules does not know of the persisted state and will not be updated.
```javascript
import store from './store'; // 1 and thus 1.1
Vue.use(timeline.plugin, { store, ... }); // 2
```
