### ISSUE TITLE
Web Storage API on top of vuex-persistenstate?

### ISSUE THREAD

**Issue by rayfoss** [robinvdvleuten/vuex-persistedstate#45]
I'm trying to make an[ authentication client side library](https://docs.feathersjs.com/api/authentication/client.html#default-options) play nice with vuex.

It can tage any Web Storage API compatible object, to save the token... has anyone managed to go full circle and implement a module with vuex-persistedstate that has all the Web Storage API methods?

**Comment by robinvdvleuten** [comment]
@rayfoss you can do it quite easily yourself if you take a look at the [customization example](https://github.com/robinvdvleuten/vuex-persistedstate#customize-storage).

**Comment by rayfoss** [comment]
Got it. There are cases where you don't need storage at all, like secure SPAs... plus it break time travel

**Comment by rayfoss** [comment]
@robinvdvleuten I just remembered what I meant. I was looking to use vuex-persistedstate with something that only takes Webstorage API, feathers-auth. The opposite of the example you linked.

The idea is that time travel would be maintained.

**Comment by hongkongkiwi** [comment]
Any answer on this? I'm looking to do the same thing.
