### ISSUE TITLE
Make compatible with IndexedDB

### ISSUE THREAD

**Issue by thomas-alrek** [robinvdvleuten/vuex-persistedstate#47]
Would it be possible to support IndexedDB for state persistanse?

**Comment by robinvdvleuten** [comment]
@thomas-alrek It would definitely be possible to support IndexedDB. I want to keep this plugin as lean as possible and let developers do the customization themselves for the implementation other than local storage. Please take a look on the [customization section](https://github.com/robinvdvleuten/vuex-persistedstate#customize-storage) in the README.
