### ISSUE TITLE
does not load saved state in nuxt

### ISSUE THREAD

**Issue by christophmayrhofer** [robinvdvleuten/vuex-persistedstate#49]
I try to use it in nuxt:

store/index:

```
let plugins = []
if(process.browser) {
    plugins = plugins.concat(createPersistedState())
}
export { plugins }
```

The state is persisted in localstorage but not loaded when I reload the page

**Comment by robinvdvleuten** [comment]
@christophmayrhofer please see my answer on issue #44; you'll probably have to use cookies as localstorage cannot be used by nuxt on server-side.

**Comment by christophmayrhofer** [comment]
I think I found the problem. In v 1.4.1 you did a check if window is undefined and if so, it used an in memory store instead. In v2 it does storage = window && window.localStorage, right away. It therefore fails on nuxt when it gets rendered on the server. Could you reenable the window check?
