### ISSUE TITLE
Small error in the 'Customize Storage' sample snippet?

### ISSUE THREAD

**Issue by oscar26** [robinvdvleuten/vuex-persistedstate#50]
Hi,

First of all, great plugin over here, I could solve my data persistence problem.

While using your plugin along with `js-cookie`, my app could not keep the state when refreshing the page and then I noticed that the `getItem` function in the provided example was using the function `Cookies.getJSON(key)` to retrieve the parsed data. So I changed it to retrieve the unparsed data (`Cookies.get(key)`) and worked beautifully.

Perhaps a little error in there or I failed to understand your plugin. Anyway, thanks again for your plugin!

**Comment by robinvdvleuten** [comment]
@oscar26 thanks for your kind words! The issue with the example is actually fixed just now by PR #52.

**Comment by oscar26** [comment]
Great! and thanks.
