### ISSUE TITLE
subscribe vs watch

### ISSUE THREAD

**Issue by FranckFreiburger** [robinvdvleuten/vuex-persistedstate#53]
Hello,
I just wondering why you are using subscribe+filter instead of watch+{ deep: true } ?

**Comment by robinvdvleuten** [comment]
Because - as mentioned this method in the [vuex documentation](https://vuex.vuejs.org/en/plugins.html) - it receives all store mutations to interact with. What the `watch` method does is very terse described. What makes you think it's a better idea to use this method?

**Comment by FranckFreiburger** [comment]
I don't know if watch is better than subscribe, I just try to understand why you made this choice.

**Comment by robinvdvleuten** [comment]
As said, I never considered watch because of the lacking documentation. Gonna close this issue now.
