### ISSUE TITLE
Caching Authorization Token for future re-use

### ISSUE THREAD

**Issue by gkatsanos** [robinvdvleuten/vuex-persistedstate#58]
Hello,

I am trying to figure out https://jsfiddle.net/robinvdvleuten/wmf8zvf8/ . 
Is there a logic hidden somewhere that takes the localStorage *if available* ? 
I am using the plugin to store a JWT (Authorization token) and as I am explicitly doing:

```js
const state = JSON.parse(localStorage.getItem('persistedState'));
const config = {
  headers: {
    Authorization: `Bearer ${state.tokens.token.accessToken}`,
  },
};

``` 

I get errors when localStorage is empty. 
Naturally I could add a condition to check for that but from your example it seems that's already part of the plugin.

**Comment by robinvdvleuten** [comment]
Could you please describe your error somewhat more? Is an API error, localstorage error, etc?

**Comment by gkatsanos** [comment]
Hey Robin, Yeah I think it was a misunderstanding from my part. 
In order for the persisted state to work,  do you need to keep a default (empty string, null, default) value in your store/index.js ?

**Comment by robinvdvleuten** [comment]
@gkatsanos yes correctly, you'll need a default "initial state" for your store.
