### ISSUE TITLE
Nested keys?

### ISSUE THREAD

**Issue by robcresswell** [robinvdvleuten/vuex-persistedstate#59]
Hey, not sure if this just my lack of knowledge about localStorage, but everything seems to be stored with a nested key at the moment, resulting in data structures like this when inspecting localStorage:

```
settings: {
    settings: {
        foo: "bar"
    }
}
```

Is this expected, or have I done something weird with the config? Note that when retrieving using the data in my application it behaves as expected, i.e. using a getter for settings gives me:

```
settings: {
    foo: "bar"
}
```

**Comment by robinvdvleuten** [comment]
@robcresswell could you explain your issue somewhat more detailed? Otherwise I can't help you.

**Comment by robcresswell** [comment]
I'm not sure how much more detail I can give. The question remains as above: is that nested key representation in localStorage expected, or is that a side effect of the library?

**Comment by robinvdvleuten** [comment]
@robcresswell I am afraid I cannot help you if you do not give an example on how you've configured the plugin

**Comment by robcresswell** [comment]
Ah I see! Sorry, I couldn't tell what you were asking for from your initial comment. Like so:

```javascript
...
import Settings from "./settings"
import persistedState from "vuex-persistedstate"

export default new Vuex.Store({
    modules: {
        settings: Settings,
        ...
    },
    plugins: [
        persistedState()
    ],
    strict: process.env.NODE_ENV !== "production"
})
```

**Comment by robinvdvleuten** [comment]
Thanks, looks like a normal setup of the plugin. How does the initial state of your settings module looks?

**Comment by robcresswell** [comment]
```javascript
    export default {
        state: {
            settings: {
                foo: "bar"
             }
        }
    }
```

As I'm looking at this, I've realised that my module imports i.e. `settings: Settings`, combined with the key `settings` in the modules state, is probably what is causing the double nesting.

**Comment by robcresswell** [comment]
Yep, that was indeed the issue, my poor refactoring when using modules. Sorry for the trouble and thanks again for the library :)

**Comment by robinvdvleuten** [comment]
@robcresswell no problemo! It's better to solve issues by questioning than by solving with code ;)
