### ISSUE TITLE
Persisting to IndexedDB

### ISSUE THREAD

**Issue by ssc-hrep3** [robinvdvleuten/vuex-persistedstate#60]
I read in your documentation about the possibility to use another persisting location (e.g. cookies). I would like to use your library to store the Vuex values into the IndexedDB. An IndexedDB uses async methods to store the data (promises). Is it possible to use this library with those setters, without introducing a racing condition?

Otherwise, I would like to open a feature request, as it seems to be more efficient to use IndexedDB over localStorage or even cookies.

What do you think about it?

**Comment by robinvdvleuten** [comment]
@ssc-hrep3 I don't know if it would work with IndexedDB, haven't used it myself. I suppose you could just implement the getters and setters yourself.

**Comment by Jerry-Merchand** [comment]
I have the same question as Sebastian had back in 2017. Has anyone actually used the IndexedDB with Robin's Vuex-PersistedState library? I too would like to do this or at least know if it's possible. Has everyone been able to just use localStorage (the default) with Vuex-PersistedState?

**Comment by boknoypatotoy** [comment]
@Jerry-Merchand the creator himself do not know if it is going to work

> I don't know if it would work with IndexedDB, haven't used it myself.

Well, it is 2020 ... he probably forgot about this project ...

try this one instead ... https://www.npmjs.com/package/vuex-persist
