### ISSUE TITLE
How could i retrieve the data from sessionStorage. the data isn't exist when the page loaded

### ISSUE THREAD

**Issue by l619534951** [robinvdvleuten/vuex-persistedstate#62]
I have tow Browser taps, tap one i had login my account and put the data to sessionStorage( tap one ), when i swith to tap two, i enter the url ( the url of tap one ) and get the data of sessionStorge from tap one, and then i put it to sessionStorage( tap two ), so i need to retieve data from sessionStorage for state. ( fresh the page could to do that, but it's not friendly from the user ), could you help me that, thank you very much.

**Comment by robinvdvleuten** [comment]
@l619534951 maybe you could provide a fiddle or jsbin with an example. I don't quite understand what you are trying to explain.

**Comment by l619534951** [comment]
just wait a minute

**Comment by l619534951** [comment]
@robinvdvleuten sorry, my english is not very good , but i am working on it.  It's messed up in my brain.  i need the way to load data in sessinStorage manually use vuex-persistedstate

**Comment by l619534951** [comment]
@robinvdvleuten [](https://jsfiddle.net/50wL7mdz/66346/), when you open this link, click the button ,and then open a new browser tap, enter this link and open that, you will found the value of message will be change, the value is equal the last browser tap's message, in the statement “_this.message = event.newValue”, I want to restore the data which is in sessionStorage to vuex's state, in my project, the data in sessionStorage is a object, It's vuex's state, so I need to restore the data to vuex's state by myself, but I dont's know how can i use this plugin to restore data( in sessionStorage ) to vuex's state by myself. by the way, i'm a student, I hope you can understand what I'm talking about, thanks.

**Comment by l619534951** [comment]
@robinvdvleuten ok，I had solved this problem by read the vuex's doc :). thanks all the same
