### ISSUE TITLE
Just curiosity

### ISSUE THREAD

**Issue by AAhrit** [robinvdvleuten/vuex-persistedstate#65]
When the plugin is using the localStorage and a refresh happends internally it is just commiting a mutation to kept in sync with the store and if I declare a mutation that mutate the state this is pick up by the plugin, if so what is the best way of doing it? I am making my own for more specific needs and I will appreciate your tips and answer. 

Are you changing the state directly from within the plugin?

By the way awesome plugin...

**Comment by robinvdvleuten** [comment]
@AAhrit The recommended way is to go full-in on the Vuex API where possible. If you're going to mutate the localStorage instance from outside Vuex, you'll end up with some pretty nifty side effects.

**Comment by robinvdvleuten** [comment]
@AAhrit So the answer your second answer, I only interact with localStorage from within the plugin. When I need to access any "persisted state" I use the getters from the Vuex.

**Comment by AAhrit** [comment]
Oh I see, but how you change the state from within the plugin in every refresh? Thanks for the answers.

**Comment by robinvdvleuten** [comment]
@AAhrit depends on what you want to do with your plugin. I use `replaceState` in my plugin as I replace the _complete_ state (localstorage merged with initial state).

**Comment by AAhrit** [comment]
When you say whenever you need to access to any "persisted state" you use Vuex getters, but this is when the state changes and you need to store what was changed? I mean you kept track any changes by watching the state through getters?

**Comment by robinvdvleuten** [comment]
I get the state changes by subscribing my plugin to Vuex

**Comment by AAhrit** [comment]
subscribing you mean adding the plugin to the `plugins` array? or subscribing to mutations like so: `store.subscribe(mutation. state)`?

**Comment by robinvdvleuten** [comment]
Yes indeed, exactly as described in the [docs](https://vuex.vuejs.org/en/plugins.html).

**Comment by AAhrit** [comment]
I'm sorry if I sound repetitive but when you access to the state you do something like this: `store.getters.count` from within the plugin? I'm guessing that if I put inside the `paths: []` array any state I want to persist it will be something like this: `paths: ['count', 'anotherCount', 'andAnotherOne']`? and lastly if I don't write down what I want to persist how you from within the plugin persist everything? I mean what is your code aproach.

**Comment by robinvdvleuten** [comment]
@AAhrit I will close this issue for now. I do not really get what you're trying to solve here. If you like to know how the plugin works try to look at the code, those hundred or so lines aren't that hard to understand.
