### ISSUE TITLE
Am I doing wrong?

### ISSUE THREAD

**Issue by julioj4pa** [robinvdvleuten/vuex-persistedstate#66]
----dados.js
import createPersistedState from 'vuex-persistedstate';
console.log(window.localStorage);
export default {
  modules:{
    usuario:{
      strict: true,
      namespaced: true,
      state:{
        tokenvuex:'',
        dadospessoais:{
          nome:'',
          telefone:'',
          docoperadora:''
        }
      },
      plugins: [createPersistedState({ storage: window.localStorage })],
      mutations:{
        inserirtoken(state, novoToken){
          state.tokenvuex= novoToken;
        },
        limpartoken(state){
          state.tokenvuex= '';
        },
        inserirdadospessoais(state, dadosnovo= {}){
          state.dadospessoais= dadosnovo;
        }
      }
    }
  }
}

---main.js
import Vue from 'vue';
import Vuex from 'vuex';

import dados from './dados';
import AppNavegador from './AppNavegador';

Vue.use(Vuex);
new Vue({
  el: '#app',
  store: new Vuex.Store(dados),
  render: h => h(AppNavegador)
});

**Comment by robinvdvleuten** [comment]
Sorry I cannot help you with this unformatted spanish looking code without a decent description.
