### ISSUE TITLE
Vuex 3 Support

### ISSUE THREAD

**Issue by jasonmj** [robinvdvleuten/vuex-persistedstate#67]
Is it possible package will support Vuex 3 in the future? Are there any specific blocking issues?
Thanks!

**Comment by robinvdvleuten** [comment]
If you read the changelog you'll see;

```
This major release only breaks backwards compatibility if you use TypeScript.
```

So I guess there will be no blocking issues and v3 will be supported.

**Comment by robinvdvleuten** [comment]
Please see release [v2.1.0](https://github.com/robinvdvleuten/vuex-persistedstate/releases/tag/v2.1.0).
