### ISSUE TITLE
Installation fails if vuex 3.0.0 is used

### ISSUE THREAD

**Issue by jrast** [robinvdvleuten/vuex-persistedstate#69]
Currently vuex-persitedstate requires vuex ^2.0.0 as peer dependency, however, it's working with vuex 3.0.0 perfectly fine. The peer dependency should be set to any version > 2.0.0

**Comment by simonjcarr** [comment]
bump. I have the same problem

**Comment by robinvdvleuten** [comment]
So feel free to fix this in a PR, shouldn't be that hard.

**Comment by robinvdvleuten** [comment]
closed by #70

**Comment by robinvdvleuten** [comment]
Please see release [v2.1.0](https://github.com/robinvdvleuten/vuex-persistedstate/releases/tag/v2.1.0).
