### ISSUE TITLE
[2.1] Persisting undefined only to localStorage

### ISSUE THREAD

**Issue by CurosMJ** [robinvdvleuten/vuex-persistedstate#73]
The value being stored in localStorage is undefined, no matter what I do. We had to lock down the version to 2.0.0 in order to allow our app to function properly. 

This is happening with 2.1.1, and not with 2.0.0. There must be something that broke in between.

I'll add more details soon.

We're using vuex 2.3.1, Vue 2.4.2.

**Comment by CurosMJ** [comment]
So far looks like the change in the storage parameter is the cause for this issue.

**Comment by robinvdvleuten** [comment]
@CurosMJ thanks for reporting! Could you give a code example of what goes wrong?

**Comment by robinvdvleuten** [comment]
@CurosMJ It is fixed by PR #75. I'll roll out a new release.
