### ISSUE TITLE
[2.1.1] Persisting undefined only to localStorage bug

### ISSUE THREAD

**Issue by ac88** [robinvdvleuten/vuex-persistedstate#74]
```javascript
import createPersistedState from 'vuex-persistedstate'

export default function ({ store }) {
  createPersistedState({paths :['user','pay.bal']})(store)
}
```

in nuxt.js plugin. this code can be vuex-persistedstate 2.0.0

i think this PR https://github.com/robinvdvleuten/vuex-persistedstate/pull/71
custom function can not support 'pay.bal' ,but it can be 'object-path' .

**Comment by robinvdvleuten** [comment]
@ac88 thanks for reporting the issue! With your description it helped me pinpoint the issue really quickly! It's fixed now and I'll roll out a new release.
