### ISSUE TITLE
Reset the state value problem

### ISSUE THREAD

**Issue by chenli1989** [robinvdvleuten/vuex-persistedstate#76]
@robinvdvleuten  I found a problem

Version: 2.1.2(latest)
Reset the state value problem

eg: 
 state.token = ''

Inside the localStorage [token]
Type is an object instead of an empty string

{"token": {}}

**Comment by robinvdvleuten** [comment]
@chenli1989 thanks for reporting the issue! Could you provide the complete localStorage token string you have? That helps me pinpointing the issue.

**Comment by chenli1989** [comment]
@robinvdvleuten  ok

Reset the state
![default](https://user-images.githubusercontent.com/8178749/32364375-6e77be84-c0af-11e7-8c0a-c3e176b47229.png)

localStorage 
![default](https://user-images.githubusercontent.com/8178749/32364321-24b2936e-c0af-11e7-9337-3c0e08c1b9ad.png)
{"token":{},"user":{},"roles":[],"permissions":[],"dicts":{}}

**Comment by robinvdvleuten** [comment]
@chenli1989 could you please try it again with v2.2.0?

**Comment by chenli1989** [comment]
@robinvdvleuten 
The reset value is resolved by the string, but the storage field in localStorage is also assigned to an empty string when the value of the state field is reset to a string

![default](https://user-images.githubusercontent.com/8178749/32366998-7a0abce0-c0bb-11e7-9b07-e339000f801d.png)

Right results:
{"token":'',"user":{},"roles":[],"permissions":[],"dicts":{}}

The result, however, is now
![default](https://user-images.githubusercontent.com/8178749/32367203-4eebe178-c0bc-11e7-91ac-ed20d689d45f.png)

**Comment by robinvdvleuten** [comment]
@chenli1989 could you maybe provide a runnable jsfiddle? You can use https://jsfiddle.net/robinvdvleuten/wmf8zvf8/ as base for this.

**Comment by chenli1989** [comment]
@robinvdvleuten  
[https://jsfiddle.net/chenli_1989/f66t2ut1/3/](https://jsfiddle.net/chenli_1989/f66t2ut1/3/)

![gif1](https://user-images.githubusercontent.com/8178749/32369819-bc58f030-c0c5-11e7-82b4-5ec8361e6e37.gif)

**Comment by robinvdvleuten** [comment]
@chenli1989 could you try it again with v2.3.0? It should be solved now.

**Comment by chenli1989** [comment]
@robinvdvleuten 
Thank you so much!
After the upgrade, the problem has been solved
