### ISSUE TITLE
BUG - Cannot use with vuex 3.0

### ISSUE THREAD

**Issue by shinrel22** [robinvdvleuten/vuex-persistedstate#79]
It throws an error when I use this plugin with vuex 3.0
Cannot read property 'storage' of undefined
I'm using vuex 3.0, vuex-persistedstate 2.3.0
How to fix this?

**Comment by robinvdvleuten** [comment]
Could you try to pass an empty object as argument?

**Comment by robinvdvleuten** [comment]
‘’’
createPersistedState({})
‘’’

**Comment by svdongen** [comment]
I tested this, `createPersistedState({})` indeed fixes this problem in my project.

**Comment by robinvdvleuten** [comment]
@svdongen good to hear! You can pull in v2.3.1 to fix this issue (https://github.com/robinvdvleuten/vuex-persistedstate/releases/tag/v2.3.1) so you don't have to provide an empty object.
