### ISSUE TITLE
support ie11? 

### ISSUE THREAD

**Issue by chenli1989** [robinvdvleuten/vuex-persistedstate#83]
**Do you want to request a *feature* or report a *bug*?**
@robinvdvleuten  Does the new version support ie11? If supported, this problem is a bug!

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

The es6 syntax appears in the compression code, resulting in the error of running The Times without supporting the es6 browser

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by robinvdvleuten** [comment]
@chenli1989 thanks for reporting the issue! Could you please tell some more about your setup? What's the error? Do you use babel to transpile your code?

**Comment by chenli1989** [comment]
@robinvdvleuten  dist/vuex-persistedstate.js  code 
`return function(n){const a=shvl.get(e,"getState",i)(t,r);`
Ie 11 reported `const a` syntax error

**Comment by robinvdvleuten** [comment]
You are absolutely right! I've fixed it with #84 👍

**Comment by robinvdvleuten** [comment]
You can install v2.3.2 and your issue should be fixed 🎉

**Comment by rodneyrehm** [comment]
re-introduced in v2.4.1: https://github.com/robinvdvleuten/vuex-persistedstate/blob/e51aa4d458b0b9e8c98ea103ef149ea7b64b954c/index.js#L56
