### ISSUE TITLE
StorageEvent

### ISSUE THREAD

**Issue by BigForNothing** [robinvdvleuten/vuex-persistedstate#85]
**Do you want to request a *feature* or report a *bug*?**
 Feature

**What is the expected behavior?**
Updates current Vuex state when a Storage Event is fired. Initialize option to enable/disable this feature.

**If this is a feature request, what is motivation or use case for changing the behavior?**
When another tab is open to the the Vue app and the state gets updated, it isn't reflected on other tabs (even though if you check localStorage, it has been updated). When a Storage object is modified (localStorage in this case), a [StorageEvent](https://developer.mozilla.org/en-US/docs/Web/API/StorageEvent) is fired. The other tabs could listen for this and update accordingly.

**Comment by robinvdvleuten** [comment]
@BigForNothing thanks for asking for a new feature! Unfortunately it is not possible to implement this as not every users uses localStorage as their storage instance. My suggestion is to listen for the event yourself in your application and dispatch a Vuex action each time it occurs.

**Comment by mp3il** [comment]
Hi,

@robinvdvleuten - I'm looking for a way to rehydrate the state after a storage event, dispatching a vuex action won't sync it, any idea what is the best way to do it?

I have 2 tabs, and I want to one of them to listen to storage changes, so when the 2nd tab is making changes, the other tab will sync and load the state from localStorage.

Just dispatching a dummy action won't cause it. is there an API for re-loading the state from storage?

Thanks.
