### ISSUE TITLE
Vuex 3 storage bug

### ISSUE THREAD

**Issue by raf1312** [robinvdvleuten/vuex-persistedstate#87]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When I try to configure the store to use Cookies like in this example: https://jsfiddle.net/robinvdvleuten/meoLa716/
 I get an error: Uncaught Error: Invalid storage instance given.
I also copied the whole const Store=... from the example and got the same error.

I use vuex v3.0.1, Vuejs v2.5.3, and vuex-persistedstate v2.3.2.

Here is a JSFiddle to show: https://jsfiddle.net/2tmr51nk/

**Comment by robinvdvleuten** [comment]
@raf1312 thanks for reporting the issue! Have you included `js-cookie` as dependency? As you've not included it in the fiddle.

**Comment by raf1312** [comment]
Hi @robinvdvleuten,

I will check it as soon as I get home.
Would be a stupid mistake...

**Comment by raf1312** [comment]
Hi @robinvdvleuten,

I used "js-cookies" instead of "js-cookie".
Now I don't get the mentioned error, but still nothing is stored as Cookie.

I will come back at you when I got time to figure out whats going on.

**Comment by robinvdvleuten** [comment]
Seems that the js-cookie issue is now resolved. Please open a new issue if you encounter something else.

**Comment by raf1312** [comment]
Hi @robinvdvleuten,

I just copied your example with "secure: true".
while testing on my local machine this couldn't work.

Now everything works fine.

Thank you.
